lib/function/trigonometry/sin.js
lib/util/bignumber.js
test/function/trigonometry/sin.test.js

It's suboptimal. However something that works, but is slow is better than nothing lol.
I played with the test cases, so that they match with the BigNumber ones (which saved me typing extra functions for already slow test cases). I also moved the `arctan` into the function section; I had mistakenly put it into the constants section of the file.
I try to catch both precisions of `2 * PI`, that of the `tau` elk and that of the `2*PI` elk. If you want me to only catch the `tau` ones I can remove lines 306 - 310.

Initial BigNumber sin support. Tests added as well.

---

lib/function/probability/factorial.js
lib/util/bignumber.js
test/function/bitwise/leftShift.test.js
test/function/bitwise/rightArithShift.test.js
test/function/probability/factorial.test.js
test/function/trigonometry/sin.test.js

I cleaned up the bignumber syntax, and fixed what was causing a bug on my local machine (also made the precisions match-up between `tau` and `pi` in order to take advantage of the memiozation).
I also realized that there was a precision carry-over error in factorial, and this has been fixed as well.

Cleanup and factorial fix.

---

lib/function/trigonometry/sech.js

Since:
```
sech(x) = 1 / cosh(x)
```
Surely these two expressions should both return `0.886818883970074`.
I'm not sure if I should rebuild `docs/`.

Fix sech example

---

lib/function/trigonometry/acos.js
lib/function/trigonometry/asin.js
lib/function/trigonometry/atan.js
lib/function/trigonometry/cosh.js
lib/function/trigonometry/sinh.js
lib/function/trigonometry/tan.js
lib/function/trigonometry/tanh.js
lib/util/bignumber.js
test/function/trigonometry/acos.test.js
test/function/trigonometry/asin.test.js
test/function/trigonometry/atan.test.js
test/function/trigonometry/cos.test.js
test/function/trigonometry/cosh.test.js
test/function/trigonometry/sin.test.js
test/function/trigonometry/sinh.test.js
test/function/trigonometry/tan.test.js
test/function/trigonometry/tanh.test.js

Implemented and tested BigNumber implementations of `acos`, `asin`, `atan`, `tan`, `cosh`, `sinh`, and `tanh`. I also fixed the test cases for `cos` to take in `1` extra bit of `pi` and they work; `tan` had a similar issue. I will refactor the others next weekend, so that they have this property as well (`tan` is all set though as can be seen in it's test cases).
While it may look like a lot, it's "only" 404 lines of code in `bignumber.js`, so hopefully it won't be too much of an eyesore to look over.

BigNumber Trigonometry

---

lib/expression/node/OperatorNode.js
test/expression/node/OperatorNode.test.js

When creating the LaTeX output for expressions like 1-(1+1) or 1-(1-1),
the bracket's where missing.

Fix missing brackets in LaTeX output (bug #273)

---

docs/expressions/customization.md
lib/expression/node/ArrayNode.js
lib/expression/node/AssignmentNode.js
lib/expression/node/BlockNode.js
lib/expression/node/ConditionalNode.js
lib/expression/node/ConstantNode.js
lib/expression/node/FunctionAssignmentNode.js
lib/expression/node/FunctionNode.js
lib/expression/node/IndexNode.js
lib/expression/node/Node.js
lib/expression/node/OperatorNode.js
lib/expression/node/RangeNode.js
lib/expression/node/SymbolNode.js
lib/expression/node/UpdateNode.js
lib/util/latex.js
test/expression/node/ArrayNode.test.js
test/expression/node/AssignmentNode.test.js
test/expression/node/BlockNode.test.js
test/expression/node/ConditionalNode.test.js
test/expression/node/ConstantNode.test.js
test/expression/node/FunctionAssignmentNode.test.js
test/expression/node/FunctionNode.test.js
test/expression/node/IndexNode.test.js
test/expression/node/Node.test.js
test/expression/node/OperatorNode.test.js
test/expression/node/RangeNode.test.js
test/expression/node/SymbolNode.test.js
test/expression/node/UpdateNode.test.js

This is a new pull request, continuing the effort in #298.
I had to make a new pull request because github got confused by my rebases.
This version simplifies the implementation while incorporating your suggestions *and* keeping my solution of passing a map of callbacks ( take a look at the documentation included in this pull request for more details ).
This is ready for review!
About passing a map of callbacks:
1. It allows having multiple maps and merging them together ( you can easily combine callbacks from several sources ).
2. It's a more intuitive UI in my opinion.
3. It's still possible to just pass a single callback if you want to.
4. It's only 9 lines of code and it can be easily replaced by a better solution in v2.
**Update:** I fixed my fix ( see commit message ). ( and the …

custom toTex

---

lib/function/probability/gamma.js

Originally it said n was an integer, but the gamma function extends the factorial functions beyond integers.

Corrected gamma documentation to allow argument to be real or complex.

---

lib/expression/node/OperatorNode.js
lib/expression/operators.js
test/expression/node/FunctionAssignmentNode.test.js
test/expression/node/OperatorNode.test.js

See #290. This add's new flags to the precedence list in `list/expression/operators.js` to disable parentheses for certain nodes only for the LaTeX output and uses those flags to simplify fractions, conditions and exponents.

Show less unnecessary parentheses in LaTeX output of OperatorNodes

---

lib/function/arithmetic/norm.js
lib/function/matrix/transpose.js
lib/type/Matrix.js
lib/type/matrix/CcsMatrix.js
lib/type/matrix/CrsMatrix.js
lib/type/matrix/DenseMatrix.js
test/function/matrix/transpose.test.js
test/type/matrix/CcsMatrix.test.js
test/type/matrix/CrsMatrix.test.js
test/type/matrix/DenseMatrix.test.js

Removed transpose() from Matrix types.
Implemented native CCS and CRS transpose()

math.transpose() refactoring

---

lib/function/arithmetic/abs.js
test/function/arithmetic/abs.test.js

This is a quick fix. This might need a better solution though (
numerical instabilities still remain ).

Fix #328 abs(0+0*i) evaluates to NaN

---

bin/repl.js
docs/command_line_debugging.md
docs/index.md

A small script that preloads mathjs and then drops the user into a REPL.
This means that I don't need to either build the dist files and do interactive debugging in the browser or run `math = require('../index');` in node anymore.
@josdejong I consider this useful but I don't know if you want little helpers like this to clutter the source tree.

Add REPL (Read Evaluate Print Loop) to ease interactive debugging

---

lib/expression/node/ArrayNode.js
lib/expression/node/AssignmentNode.js
lib/expression/node/BlockNode.js
lib/expression/node/ConditionalNode.js
lib/expression/node/ConstantNode.js
lib/expression/node/FunctionAssignmentNode.js
lib/expression/node/FunctionNode.js
lib/expression/node/IndexNode.js
lib/expression/node/Node.js
lib/expression/node/OperatorNode.js
lib/expression/node/RangeNode.js
lib/expression/node/SymbolNode.js
lib/expression/node/UpdateNode.js
lib/expression/parse.js
lib/expression/transform/filter.transform.js
test/expression/node/ArrayNode.test.js
test/expression/node/AssignmentNode.test.js
test/expression/node/BlockNode.test.js
test/expression/node/ConditionalNode.test.js
test/expression/node/ConstantNode.test.js
test/expression/node/FunctionAssignmentNode.test.js
test/expression/node/FunctionNode.test.js
test/expression/node/IndexNode.test.js
test/expression/node/Node.test.js
test/expression/node/OperatorNode.test.js
test/expression/node/RangeNode.test.js
test/expression/node/SymbolNode.test.js
test/expression/node/UpdateNode.test.js

This removes the use of `instanceof` for nodes. Therefore the `Node.isNode()` function got replaced by a boolean property `isNode` and every node has it's own property, like `isSymbolNode` for example.
See  #345

Get rid of instanceof for nodes

---

lib/function/utils/partitionSelect.js
lib/math.js
test/function/utils/partitionSelect.test.js

It currently uses Quickselect. I noticed that for `median` (which `quantileSeq` inherited some code from), the library currently sorts the entire array. This would takes steps to avoid that unnecessary of computation.

Implemented a partition-based selection function

---

bin/cli.js
docs/command_line_interface.md

This adds a `--parenthesis=` option to the command line.

Expose the parenthesis option via the command line

---

lib/function/statistics/median.js
lib/function/statistics/quantileSeq.js

This brings the average case down to *O(n)* from *O(nlogn)*.
Also, removed the flatted call in `median` for a sequence (still needed for an Array or Matrix input), and added a few more comments in `quantileSeq`.

Replaced the sort in median and quantileSeq with a partition-based selection function

---

docs/expressions/customization.md
lib/expression/node/FunctionNode.js
lib/util/latex.js
test/expression/node/FunctionNode.test.js

This enables attaching `toTex` handlers to the different functions. A `toTex` handler can be one of the following (as already used in `util/latex.js`):
* A callback function
* A template string
* An object cotaining template strings or callback functions for different numbers of arguments.
This is still missing documentation. This will enable moving all of the LaTeX output in `util/latex`'s `exports.functions` to the definitions of the functions themselves later on.

Attach 'toTex' to functions

---

docs/expressions/expression_trees.md

FunctionNode has `name: string` property instead of `symbol: Node`

Documentation fix

---

lib/type/unit/Unit.js
test/type/unit/Unit.test.js

I found that by NOT setting the charset in the html file (which I fail to do literally every time), the default symbol for ohm, `U+03A9 Ω` (greek capital letter omega), as a variable name, breaks the entire script. Not to mention it's difficult to type `Ω` on a keyboard.
I removed `Ω` as a unit and created a new prefix list for `ohm` that accepts both short and long prefixes, so both `Mohm` and `megaohm` are acceptable. I <i>think</i> the `_bestPrefix` function will always choose the short prefix over the long one.

Removed UPPERCASE OMEGA character (breaks browsers)

---

examples/units.js
lib/type/unit/Unit.js
test/type/unit/Unit.test.js

@ericman314 I came across two topics we need to discuss before releasing support for derived units:
- `Unit.parse` did handle precedence of division higher than implicit multiplication, i.e. `1 m / kg s` was parsed as `(1 * m) / (kg * s)`. The precedence of implicit multiplications is ambiguous in mathematics (does `1/2x` mean half x or a half divided by x?). With math.js we choose to handle implicit multiplication with the same precedence as divisions ([see docs](http://mathjs.org/docs/expressions/syntax.html#precedence)), so `1 m / kg s` would be parsed as `((1 * m) / kg) * s`. Both parsers should work consistent. Would it be ok with you if we change `Unit.parse` such that it handles implicit multiplication with the same precedence as division, see this PR?
- `Unit.parse` previously …

Some behavioral changes for Unit.parse

---

docs/datatypes/units.md
lib/type/unit/Unit.js
test/type/unit/Unit.test.js

- Added support for parentheses to `Unit.parse` (this fixes `fromJSON`)
- Updated unit tests
- Updated docs to warn about implicit multiplication such as: `8.314 m^3 Pa / mol K`

Added support for parentheses to Unit.parse

---

lib/utils/object.js

We ran into an issue where in IE8, `canDefineProperty()` would return true, and then our application would throw an error in `es5-sham` (https://github.com/es-shims/es5-shim/blob/master/es5-sham.js#L421).
This change ensures `canDefineProperty()` will return false in IE8 (as using `get` will throw an error at that specific line in `es5-sham`).  Let me know if you want me to write tests or anything else!

Update defineProperty check

---

docs/datatypes/units.md
examples/units.js
lib/function/arithmetic/abs.js
lib/function/arithmetic/cube.js
lib/function/arithmetic/sign.js
lib/function/arithmetic/sqrt.js
lib/function/arithmetic/square.js
test/function/arithmetic/abs.test.js
test/function/arithmetic/cube.test.js
test/function/arithmetic/sign.test.js
test/function/arithmetic/sqrt.test.js
test/function/arithmetic/square.test.js

- Added support for units to abs, cube, sign, sqrt, square
- Updated examples, docs, and unit tests
- Added a lengthy discourse to `docs/datatypes/units.md` on why not to use `degF` and `degC` in computations
- sqrt does not work for negative units: `math.eval('sqrt(-4 m^2/s^2)') = NaN m / s`
Are there any other functions we should add units support to?

Added support for units to abs, cube, sign, sqrt, square

---

lib/function/arithmetic/divideScalar.js
lib/type/unit/Unit.js
lib/type/unit/physicalConstants.js
test/function/arithmetic/divide.test.js
test/function/arithmetic/dotMultiply.test.js
test/function/arithmetic/multiply.test.js
test/type/unit/Unit.test.js
test/type/unit/physicalConstants.test.js

This ended up being quite a few changes, so I'll submit the PR without merging it yet.
- Best prefix is applied for units like `3e9 m^2` and `5e-8 s^-1` and so on
- Physical constants are all `fixPrefix == true` now (via the undocumented `_fix` function)
- Minor bug fixes

Unit prefix powers

---

lib/type/matrix/SparseMatrix.js
test/type/matrix/SparseMatrix.test.js

Fixes an issue with `new types.SparseMatrix()`; currently the size defaults to `[0]`, which causes some odd issues, which are fixed by defaulting the size to `[0, 0]`.  For example:
```
var m = new math.types.SparseMatrix();
m.resize([2, 2]);
m.set([1, 1], 42);
m.get([1, 1]); //Currently returns 0, rather than 42 as expected
```

Fix a small bug with new types.SparseMatrix()

---

lib/function/arithmetic/abs.js
lib/function/arithmetic/cbrt.js
lib/function/arithmetic/multiplyScalar.js
lib/type/complex/Complex.js
lib/type/unit/Unit.js
lib/type/unit/function/unit.js
test/function/arithmetic/abs.test.js
test/function/arithmetic/addScalar.test.js
test/function/arithmetic/cbrt.test.js
test/function/arithmetic/divide.test.js
test/function/arithmetic/multiply.test.js
test/function/arithmetic/sign.test.js
test/function/arithmetic/sqrt.test.js
test/function/arithmetic/subtract.test.js
test/function/arithmetic/unaryMinus.test.js
test/function/trigonometry/cos.test.js
test/function/trigonometry/cosh.test.js
test/function/trigonometry/cot.test.js
test/function/trigonometry/coth.test.js
test/function/trigonometry/csc.test.js
test/function/trigonometry/csch.test.js
test/function/trigonometry/sec.test.js
test/function/trigonometry/sech.test.js
test/function/trigonometry/sin.test.js
test/function/trigonometry/sinh.test.js
test/function/trigonometry/tan.test.js
test/function/trigonometry/tanh.test.js
test/type/unit/Unit.test.js

Added support for complex-valued units.
Added unit tests.
Issues:
Docs not updated yet.
Unit constructor not able to parse a complex-valued unit, such as `"(2 + 3i) kg"`.
Units `VA` and `VAR` have not been added yet.

Added support for complex units

---

lib/expression/node/ConditionalNode.js
test/expression/node/ConditionalNode.test.js
test/expression/node/OperatorNode.test.js

While discussing how the LaTeX output of ObjectNodes should look like, I thought that the `cases` environment should be used for ConditionalNodes, not the `array` environment.
This pull request doesn't change what the ConditionalNode looks like (except for one space character after the "if").

ConditionalNode: simplify LaTeX by using the 'cases' environment

---

lib/function/geometry/intersect.js
test/function/geometry/intersect.test.js

This fixes the numerically unstable math.intersect() for the 2
dimensional case by computing whether the determinant is within
config.epsilon instead of a hard equality check.

Fix #540: math.intersect() is numerically unstable

---

lib/function/arithmetic/pow.js
test/function/arithmetic/pow.test.js

Here's an experiment with `realmode` option for exponentiation.
Example:
```js
console.log(math.eval('(-8)^(2/3)').toString());
math.config({realmode:true});
console.log(math.eval('(-8)^(2/3)').toString());
```
Output:
```
-1.9999999999999987 + 3.464101615137754i
3.9999999999999996
```
Let's try this out and see how it feels and make sure everything seems right with this. We can change the name of `realmode` too, or use an existing option like `predictable`, or whatever. When we are satisfied with it then I will add some notes to the docs before you merge the PR.

Realmode exponentiation

---

lib/type/unit/Unit.js

Removes `PREFIX_NONE` from `Unit.js`, which is almost but not quite the same as `PREFIXES.NONE`, and which causes things to break if used as the prefix in a custom unit.

Removed PREFIX_NONE

---

docs/expressions/customization.md
examples/browser/pretty_printing_with_mathjax.html
lib/expression/node/OperatorNode.js
lib/expression/node/ParenthesisNode.js
lib/expression/parse.js
test/expression/node/OperatorNode.test.js
test/expression/node/ParenthesisNode.test.js
test/expression/parse.test.js
test/function/unit/to.test.js

See #607 
~~**NOTE**: I wasn't able to test the new pretty printing browser example because of the Same Origin policy and because I got a syntax error in the bundled `math.js`. This syntax error also happens when running `npm run build` on the development branch.~~
Now it works, using a local webserver.

Options for `toTex` and `toString` output of implicit multiplications

---

lib/type/unit/Unit.js
test/function/arithmetic/divide.test.js
test/type/unit/Unit.test.js

Unit-less units are now converted to numeric values when predictable:false, which addresses #651.

Unit-less units become numeric values when predictable:false

---

docs/datatypes/units.md
lib/type/unit/Unit.js
lib/type/unit/function/createUnit.js
lib/type/unit/index.js
test/type/unit/Unit.test.js
test/type/unit/function/createUnit.test.js

Create a user-defined unit. The user supplies the name of the new unit, the definition in terms of existing units, and options such as prefixes and aliases.
```js
math.createUnit('knot', '0.514444 m/s', {aliases: ['knots', 'kts', 'kt']})  // knot
math.eval('4 week to createUnit("fortnight", 14 days)')  // 2 fortnight
```
TODO:
Units are installed directly in the global `math.type.Unit` scope, so you can't use different sets of user-defined units in multiple scopes at the same time like you can with user-defined variables. Supporting this might be time consuming and not very much worth it.
Currently the only validation done on names of new units is to check for collisions with other units. We might want to add checks for collisions with built-in functions, and to check for valid characters …

Create user-defined units

---

lib/function/string/print.js

Add missing 'Object' type definition to third parameter. Fixes #700

Fix print options argument type

---

docs/datatypes/units.md

Just a minor correction that fixes a call from `math.Unit` -> `math.unit`

Fix incorrect case

---

lib/function/matrix/cross.js
test/function/matrix/cross.test.js

Squeeze arrays before attempting to cross them so that n-dimensional
vectors can be cross multiplied (as long as only one direction has a
series of 3 elements)
See issue #713

Extend cross() to support n-d vectors

---

lib/type/unit/Unit.js
test/function/arithmetic/divide.test.js
test/function/arithmetic/dotDivide.test.js
test/type/string.test.js
test/type/unit/Unit.test.js
test/type/unit/function/unit.test.js

Units no longer search for the best prefix if the current prefix results in a value approximately between 0.1 and 1000.
Added some tests and adjusted others. Some tests were simplified as a result of the units not changing prefixes.

Retain original units

---

lib/expression/node/OperatorNode.js
test/expression/node/OperatorNode.test.js

Support more than two operands in OperatorNode for addition and multiplication

---

docs/expressions/expression_trees.md

Hey,
looks like in the samples from `expression_trees.md`,
some parentheses are missing in the sample code.

add missing parentheses

---

lib/function/matrix/kron.js
test/function/matrix/kron.test.js

Just changing from:
```javascript
y * x
```
to 
```javascript
math.multiply(y,x)
```
So Complex Numbers are supported.
Also added a unit test, so it all works.
Any feedback or things to change just say! 😄

Add Support for Complex Numbers in Kronecker Product Function

---

lib/type/unit/Unit.js

When packaging this library with `rollup.js` - there is a continual complaint about importing a "node built-in" `util`, which stems from this line in `Unit.js`. The line appears extraneous, however - so this PR simply removes it.

Remove extraneous `require('util')` from Unit.js

---

lib/function/matrix/index.js
lib/function/matrix/reshape.js
lib/type/matrix/DenseMatrix.js
lib/type/matrix/ImmutableDenseMatrix.js
lib/type/matrix/Matrix.js
lib/utils/array.js
test/function/matrix/reshape.test.js
test/type/matrix/DenseMatrix.test.js
test/type/matrix/ImmutableDenseMatrix.test.js
test/type/matrix/Matrix.test.js
test/utils/array.test.js

Contains implementation of `reshape()` (see #725). While very similar to `resize()`, this will retain all elements and requires the product of the dimensions to be the same (2x2 -> 1x4, 3x2x4 -> 12x2).
`reshape()` has been added as a global function `math.reshape()`, as well as a method on DenseMatrix `new DenseMatrix([[1, 2], [3, 4]]).reshape([1, 4])` for convenience.
Every location in which `reshape()` has been added contains a corresponding set of tests.
**Note**: I haven't figured out an efficient method for reshaping a sparse matrix, so for now the `SparseMatrix.reshape()` method does not exist.
Closes #725

Implementation of reshape()

---

lib/function/matrix/reshape.js
lib/type/matrix/SparseMatrix.js
test/function/matrix/reshape.test.js
test/type/matrix/SparseMatrix.test.js

Here is an implementation of reshape for the SparseMatrix.
`math.reshape` has also been changed to use each matrix type's implementation of `reshape`, if it exists, or the `array.reshape` function otherwise (which was the original behavior).

SparseMatrix.reshape

---

lib/function/algebra/decomposition/lup.js

Fixes #801.
Return type documented as it is done for: http://mathjs.org/docs/reference/functions/slu.html.
Still not entirely clear what is returned by the function without looking at example though. Especially regarding the permutation matrix - a matrix isn't actually returned just the position of ones which the documentation does not mention.

Changes to lup docs to fix error.

---

docs/datatypes/units.md
lib/type/unit/Unit.js
test/type/unit/Unit.test.js

Adds the Unit method `toSI`, which returns a clone of the unit converted to base SI units. Also adds docs and unit tests.

Added Unit.prototype.toSI

---

lib/function/arithmetic/pow.js
test/function/arithmetic/pow.test.js

Goes someway towards addressing #804.
Tests pass with current behaviour of complex.js and will need updating when full support of infinite numbers is added there.
New behaviour of pow function:
* `(-2)^Infinity = ComplexNAN`
* `(-1)^Infinity = ComplexNAN`
* `(-0.5)^Infinity = 0` (real)
* `(-2)^(-Infinity) = 0` (real)
* `(-0.5)^(-Infinty) = ComplexNaN`
If `config.predictible = true` results are the same but `ComplexNaN` becomes `NaN`.

Extension of pow function to support Infinite exponents.

---

lib/function/algebra/simplify.js

I noticed that 'v' and 'C' have the exact same behaviour as wildcards in simplify rules. I think the original plan was to make 'v' match SymbolNodes that are not built-in constants but that was never implemented. I've arbitrarily removed 'C' here.
This may be a breaking change if people are already using a 'C' wildcard in their own simplify rules, although I never saw any documentation for using the 'C' wildcard so I think it's unlikely. I figured it's not worth putting a deprecation warning first.

Remove redundant rule wildcard variable 'C' from simplify

---

lib/function/algebra/simplify.js

It is currently possible for rules to rewrite the expression like A->B then B->A the next loop, but the termination condition for `simplify` only looks for A->A, which would cause and endless simplifying loop. This should fix that scenario.

Fix terminate condition of simplify to avoid endless loops

---

lib/function/geometry/intersect.js
test/function/geometry/intersect.test.js

The equation to find the value of ’t' for the intersection of a line and a plane does not appear to be entirely correct.  Please double-check.

Fixed Bug in Equation For Intersection of Line and Plane

---

docs/datatypes/complex_numbers.md
examples/complex_numbers.js
lib/function/relational/compare.js
lib/function/relational/larger.js
lib/function/relational/largerEq.js
lib/function/relational/smaller.js
lib/function/relational/smallerEq.js
lib/function/statistics/median.js
lib/type/complex/Complex.js
test/function/relational/compare.test.js
test/function/relational/larger.test.js
test/function/relational/largerEq.test.js
test/function/relational/smaller.test.js
test/function/relational/smallerEq.test.js
test/function/statistics/max.test.js
test/function/statistics/median.test.js
test/function/statistics/min.test.js
test/type/complex/Complex.test.js

Allows comparison of Complex Numbers with number, BigNumber, and Complex Number
This behavior is reflected in the following functions
`compare`, `larger`, `largerEq`, `smaller`, `smallerEq`, `max`, `min` and `median`
Note: `median` gives a Complex Number as result if the first argument is a Complex Number

support to compare complex numbers #837

---

docs/getting_started.md

Added line in doc and changed the comment in the code example in case `// use math.js` was misread as `// use mathjs`.
Fixes #878

Clarify name of global variable in docs

---

lib/expression/parse.js

Small modification to `parse.js`, which checks if the token causing the syntax error is `'` and if so informs the user that double quotes are required for strings.
I reckon this is common gotcha and it would save users time if the syntax error message gives a heads up.
`math.parse("6 + '4'")` gives 
- Previous behaviour: `SyntaxError: Value expected (char 5)`
- New behaviour:  `SyntaxError: Value expected - note strings must be enclosed by double quotes (char 5)`

Syntax error includes hint if single quotes are used for a string

---

lib/expression/node/ObjectNode.js
lib/utils/customs.js
test/expression/security.test.js
test/utils/customs.test.js

Restore access to inherited properties and methods removed by the recent security fixes.
Fixes #886
**I am not a security expert so please do review these changes carefully.**
The most significant changes are in c4951c2, commit message:
```
To safely restore inherited properties and methods on plain objects e.g
with Object.create, some overly broad conditions need to be removed and
others added to more explicitly exclude unsafe properties.
isSafeMethod() has been modified as bellow, roughly the same conditions
are also now used in isSafeProperty() for get/setSafeProperty() which
previously restricted all inherited properties.
- Require __proto__ to have own-method
Intended to prevent ghosting of class methods, but also prevents
access to properties from further up the chain.
+ Require any …
```

Prototyped Scopes

---

lib/utils/customs.js
test/expression/security.test.js
test/utils/customs.test.js

Change condition for property ghosting to match desired behaviour as discussed in #888 :
- Ghosting custom properties are allowed
- Only ghosting properties on Function.prototype or Object.prototype are restricted

Update isSafeProperty ghosting

---

lib/utils/customs.js
test/expression/security.test.js
test/utils/customs.test.js

From discussion in #888 diallowing ghosting causes problems with natives such as `length` which is both an own property and on the prototype chain and on the root Function.prototype/Array.prototype etc.
There don't appear to be any security concerns for ghosting properties, only for methods.

Remove ghosting from isSafeProperty

---

lib/type/complex/Complex.js

I think you are trying to match the '-' symbol in an negative imaginary number of complex number, but using /[\b-.]/ as regex instead of /[-]/, right?
I found this because of an Exception('org.mozilla.javascript.EcmaError: SyntaxError: Invalid range in character class') appears while I was trying to evaluate math.js with Mozilla Rhino.

Fixed the regex for the '-' symbol in an negative imaginary number

---

lib/type/unit/Unit.js
test/type/unit/Unit.test.js

This should close #901 . There is a separate issue breaking unit tests when run all at once, which I'll be filing shortly.

Simplify units before returning numeric value

---

lib/expression/node/OperatorNode.js
test/expression/node/OperatorNode.test.js

Auto implicit fixes

---

lib/function/algebra/simplify.js
test/function/algebra/simplify.test.js

I randomly stumbled upon this by noticing that the last expression I've added in the unit test (`8 * x ^ 9 + 2 * (x ^ 3) ^ 3`) doesn't simplify to `10 * x ^ 9` as expected.

Simplify nested exponentiations

---

lib/function/algebra/simplify.js
test/function/algebra/simplify.test.js

Currently, expressions such as `10 - (x - 2)` and `x - (y + x)` are not at all simplified. The reason why is the outer negation turns into a multiply by `-1`, but this blocks the flattening of the entire expression, so the outer and inner like terms never get a chance to combine.
This pull request adds an additional rule to `simplify` that allows for this flattening to take place by distributing the `-1` factor over the inner terms. While this does fix the cases above (simplifying them to `12 - x` and `-y`, respectively) and related expressions, it does not help with expressions such as `10 - 5 * (x - 2)`. However, the more general cases (such as this one) are more difficult, since we cannot guarantee that these transformations will be useful (consider `10 + (y + 2) * (y - 2)`, should …

Added rule to simplify that allows for combining of like terms in embedded quantities

---

lib/function/algebra/simplify/simplifyConstant.js
test/function/algebra/simplify.test.js

When `simplify` (or more specifically, `simplifyConstants`) is given a function with more than two arguments, it binarizes the function calls; that is, `simplify("f(x, y, z)")` evaluates to `f(f(x, y), z)`. This is not correct (unless the function happens to be associative), and can even potentially cause the expression to become malformed if `f` requires three arguments.
Additionally, there is a bug where evaluating `simplify("f(4)")` with `f` undefined will throw an error, where `simplify("f(x)")` and `simplify("f(4,5)")` will evaluate fine.
This PR fixes both of these issues: it only allows the functions `add` and `multiply` to become binarized, and will handle undefined unary functions without throwing an error. Please let me know if this PR needs any other improvements, or if there …

Do not let `simplifyConstants` binarize functions with more than two arguments

---

lib/function/algebra/derivative.js
package-lock.json
test/function/algebra/derivative.test.js

Extends the rules for '+' and '*' to correctly handle `OperatorNode`'s with three arguments.
Adds tests for these cases.
See #1002

Improves derivative for 3 argument nodes. Closes #1002

---

lib/expression/node/OperatorNode.js
test/expression/node/OperatorNode.test.js

I confused travis with #1028 so here I am trying again.
When calling `map` on an `OperatorNode` with `implicit === true` and `OperatorNode` with `implicit === false` is created.

Bug: When mapping an OperatorNode implicit status is lost

---

lib/expression/parse.js
test/expression/parse.test.js
test/expression/security.test.js

Remove support for calling a function returned by a function, parse as implicit multiplication instead. 
See #1035

Evaluate `sqrt(2)(3)` as implicit multiplication instead of function call

---

HISTORY.md

Version 4.0.1 released 1 year and 2 days ago, according to HISTORY.MD

Time Traveling is Real!!

---

examples/browser/plot.html

https://wzrd.in is down and so example breaks.
This commit uses unpkg instead which should be more reliable although I can't work out how the build the website so I haven't tested this actually works.
closes #1073

Uses unpkg.com instead of wzrd for cdn. 

---

lib/function/arithmetic/norm.js
test/function/arithmetic/norm.test.js

As mentioned in #1094 
The code on line 195 of `lib/function/arithmetic/norm.js` is comment with `sqrt(sum(diag(x'x)))` but this is only true for the conjugate transpose. The general formula is `sqrt(sum(sum(pow(abs(a[i,j]),2),i=1..m),j=1..n))`, the square root of the sum of the absolute values squared of the entries.
This commit makes mathjs agree with matlab, and improves the efficiency by directly summing a[i,j]' * a[i,j]. The old method was cubic (for square matrices); this method is quadratic. I also added a short test.
In mathjs 5.2.1:
```js
math.eval('norm([[3+4i]],"fro")')
{ re: 3, im: 4 }
```
In matlab:
```matlab
norm([[3+4i]],'fro')
ans =  5
```
After this commit, mathjs outputs 5.

Bugix for Frobenius norm of complex matrices.

---

lib/expression/embeddedDocs/function/matrix/ctranspose.js
lib/expression/embeddedDocs/index.js
lib/expression/parse.js
lib/function/matrix/ctranspose.js
lib/function/matrix/index.js
lib/utils/latex.js
test/function/matrix/ctranspose.test.js

As mentioned in #1094:
In matlab and octave the expression A' produces the Hermitian
conjugate, the complex conjugate of the transpose.
Now transpose produces the transpose, while ctranspose produces
the conjugate transpose. These are equal for real numbers, while
for complex numbers only the conjugate transpose is of much use.

Add complex transpose. A' now takes conjugate.

---

lib/utils/bignumber/formatter.js
lib/utils/number.js

Internet Explorer 11 does not support Object.assign, as this is a browser that is _meant_ to be supported by mathjs we should probably use this ponyfill.
I have added a new dependancy in this commit (https://www.npm.com/package/object-assign) as I thought it made sense to not reinvent the wheel here.
If we ever start transpiling mathjs we would then be able to revert this commit.
This will fix some of the tests failing on IE 11 in #1105.

Ponyfill Object.assign

---

lib/function/matrix/det.js
test/function/matrix/det.test.js

Uses the LU decomposition to calculate the determinant.
Also added a test to verify that determinants of sparse matrices are calculated correctly.
Addresses #908, although more improvements are certainly possible.

Improved performance of determinant

---

README.md

README now includes info about local browsertests and browserstack as well as a note explaining that a valid BrowserStack login is needed to run the tests there.
closes #1116.

add note to readme about browser testing.

---

.npmignore
package.json

Rather than add everything to the npm package it is better to only add the nessary files.
This commit lists the files to include based on https://docs.npmjs.com/files/package.json#files
Note that to test this you would have to publish an npm module and manually check that it works.
I propse adding this to v5 #1045.

explicity list files to be included in npm package

---

.travis.yml
package.json

Off the back of adding linting in #1129 this PR creates a new travis build step for it.
This means that folk can easily see the difference between linting failures and test failures.
Test will only be run when linting passes, this also means that linting runs once instead of four times.
---
I also changed the name of the browser-test stage for consistancy

Lint build stage

---

.travis.yml

Travis should execute `npm run test:src` once for each version of node.
Hopefully this commit ensures that that is the case.
---
closes #1133

run correct test script.

---

src/type/unit/Unit.js

When this error is encountered in the field, I see it via honeybadger, but I have none of the context about what unit it was called in, and what unit it was being converted to. Help the debugging by adding some info to the exception. 
I'm not entirely sure that 'toString' is what I want here - perhaps others in the community can help make that the right expression?

Improve debugging support

---

test/function/algebra/rationalize.test.js

- Reduces the complexity of the power expansion test example.
- Moves one particually slow example to a skipped test.
- Removes the timeout as it is no longer needed.
closes #1142

Decrease runtime of rationalize tests.

---

package-lock.json
src/constants.js
test/constants.test.js

Recently I wanted to bundle MathJS *with* constants but *without* complex numbers. This PR adds a check to see if `type.Complex` is loaded before adding `i` to the constants.
I also restructured `constants.test.js` a bit so that each instance of MathJS undergoes all the appropriate tests, including a new instance without `i`.

enable bundling constants without complex

---

docs/expressions/algebra.md
docs/getting_started.md
src/function/algebra/decomposition/qr.js
src/function/combinatorics/stirlingS2.js

Thought there might be some other broken links so I asked a crawler to find them for me :nerd_face:. Fixed them except for links to contributors. I assumed all broken link in `docs/reference/functions` were built automatically so had to be fixed in jsdoc.

fix some broken links

---

src/type/bignumber/BigNumber.js

BigNumber imports `decimal.js/decimal.js`, which uses the ES5 bundle for the library. Since it's now possible to do ES6 imports, we should be able to switch this over to the ES6 version.
This is of interest to me because a project I'm working on uses the ES6 bundle of decimal.js for other things, and we're trying to avoid having to ship both bundles. Because of that, I just changed this one import - I'm not sure what your plans are for using es6 imports elsewhere, if you want to migrate more of the imports I might be able to help with that.

Change decimal.js import

---

src/utils/array.js

So I notice that in this comment [here](https://github.com/josdejong/mathjs/issues/1148#issuecomment-404037975), reshape is terribly slow compared to transpose. The issues lies mainly with how slow the recursion is, and thus, a friend of mine rewrites the reshape function iteratively instead, and the speed boost is immense. 
Here is the log of performance for the transpose of var a = math.ones(1, 100000) :
Call to algorithm for transpose took 67.26909599999993 milliseconds. 
Call to old algorithm for reshape took 6013.208004 milliseconds.
Call to new algorithm for reshape took 117.086568 milliseconds.
Here is the log of performance for reshape for converting 1 x 10000 to 1000 x 100 shape:
Call to old algorithm for power took 7273.37094 milliseconds.
Call to new algorithm for reshape took …

Speed up reshaping function of a matrix

---

.travis.yml

Fixes issues we are having with greenkeeper, `npm ci`, and lock files.
Solution based on https://github.com/greenkeeperio/greenkeeper-lockfile#npm.
Should prevent CI failures in greenkeeper's PR #1183.
Greenkeeper issue: https://github.com/greenkeeperio/greenkeeper-lockfile/issues/156.
@josdejong How tight should we be on the npm and greenkeeper-lock file versions?

Help greenkeeper to manage lockfiles

---

.travis.yml

Reduces number of build stages (3 -> 2) and adds testing of the mathjs bundle.
I could not find a way to go to one build stage without running linting, browser tests and the bundle test on all three versions of node. This repetition would slow the CI run down to the point where it defeats the point of parallelising these tests.

Improve CI testing

---

package.json

`package.json` suggested we support node 4. Alas we don't.

fix: mathjs requires node 6

---

HISTORY.md

As it says on the tin. The main reason I make this PR is my editor made this change for me so merging it as a PR might save noise if anyone edits the file in the future.

remove trailing whitespace in HISTORY.md

---

src/expression/parse.js
test/expression/parse.test.js

* Allow object literal expression be multiple lines
* Add test for multiple lines object literal

Fix object literal enable multiple lines (#1328)

---

gulpfile.js

It turns out webpack can error in two ways. This adds a check for the second way
and also surfaces any warnings.
Previously if webpack failed to build mathjs it silently failed and gulp crashed later on (when trying to minify).
See: https://webpack.js.org/api/node/#error-handling.

Improve error handling if webpack errors.

---

src/expression/node/RelationalNode.js
test/expression/node/RelationalNode.test.js

The parameters were being output using toString(), rather than toTex().

Fix incorrect LaTeX output of RelationalNodes

---

src/type/unit/Unit.js

Separate bit prefixes into SI (base 1000) and IEC (base1024). These are `BINARY_SHORT_SI`, `BINARY_SHORT_IEC`, `BINARY_LONG_SI` and `BINARY_LONG_IEC`. 
* `BINARY_LONG_SI` and `BINARY_LONG_IEC` are combined into `BINARY_LONG` 
* `BINARY_SHORT_SI` and `BINARY_SHORT_IEC` are combined into `BINARY_SHORT`
This is done in the same manner as combining `PREFIXES.SHORT` and `PREFIXES.LONG` into `PREFIXES.SHORTLONG`. This PR aims to progress towards a solution for #1300.

Separating Binary Prefixes

---

gulpfile.js

Replace placeholders @date and @version with their appropriate values in `lib/header.js`
This is to support custom bundling, so the license won't have unresolved placeholder values.
Related: https://github.com/josdejong/mathjs/issues/1442

Fix banner/license for custom bundling

---

src/type/unit/Unit.js
test/type/unit/function/unit.test.js

This PR implements #1209 and #1043
In a few words:
- added new `BASE_UNITS.SOUND_VOLUME` base
- added bel and decibel units
- added tonne (equals to t)
- fixed candela prefixes

Fixed tonne and candela units, added bel and dB

---

package.json

mathjs already has a UMD build, which is great, but JavaScript CDNs like unpkg and jdelivr aren't able to locate it off the bat. This PR adds the unpkg and jsdelivr fields they use to locate browser builds, so that folks using AMD loaders like `d3-require` can easily load mathjs.

Add unpkg and jsdelivr fields pointing to UMD build

---

README.md

If a greenkeeper branch is failing we don't want kids to get the wrong impression about
the quality of code landing on master in mathjs!
Currently the badge reflects the status of the last travis run for any branch of mathjs.

tie build status badge to master

---

src/expression/node/IndexNode.js
test/unit-tests/expression/node/IndexNode.test.js

This isn't currently happening.

Copy IndexNode dotNotation property in map and clone methods

---

docs/expressions/expression_trees.md

This PR corrects the example provided for `toHTML()` method in the  `docs/expressions/expression_trees.md`.
Earlier `toString()` was written in place of `toHTML()`.

`toHTML()` method example corrected.

---

src/function/algebra/simplify.js
test/unit-tests/function/algebra/simplify.test.js

Is this all that's needed to fix [#1725](https://github.com/josdejong/mathjs/issues/1725)? Unsure if I've added the rule in the right place.

Let simplify handle a/(b/c)

---

HISTORY.md

Whitespace hidden diff is empty: https://github.com/josdejong/mathjs/pull/1775/files?diff=split&w=1

remove trailing space in HISTORY

---

test/node-tests/cli/cli.test.js

Shouldnt provide any issues for other systems I hope but we'll see what the various checks think

Prefix the cli test with 'node' so it works on windows

---

src/type/unit/Unit.js
test/unit-tests/type/unit/Unit.test.js

Fix for #1808 
@ericman314 is this a proper fix? Or should we not allow unitless units in the first place?

Fix #1808: `toNumber()` not working on a unitless unit

---

src/function/matrix/eigs.js

The matrix `math.eigs(H).vectors` contains the eigenvectors as columns, not rows, as previously suggested.
Also includes example of how to access the relevant vectors using `math.column`.
Closes #1844

Clarify `eigs` documentation

---

package-lock.json
package.json
src/function/probability/util/seededRNG.js
test/node-tests/treeShaking/treeShaking.test.js

For issue #1949 , replace the seed-random by seedrandom.
- I have no idea about which is better of [the fast PRNG algorithms](https://github.com/davidbau/seedrandom#other-fast-prng-algorithms) supported by seedrandom, so I choose the default.
- The bundle size increases a little, so I change the `maxSize` up.
I've run the `build-and-test` locally. Looks no error.

Replace seed-random by seedrandom

---

src/function/arithmetic/mod.js
src/type/bignumber/BigNumber.js
test/unit-tests/function/arithmetic/mod.test.js

This fixes incorrect `mod` behaviour for BigNumbers and Fractions, as described in issue #1964.

Fix negative dividend modulo for BigNumber and Fraction

---

src/function/matrix/sqrtm.js
test/unit-tests/function/matrix/sqrtm.test.js

Fixes #1597
Just used this https://github.com/josdejong/mathjs/issues/1597#issuecomment-522934657

sqrtm - throw an error for matrices with dimension greater than two

---

src/function/probability/pickRandom.js
test/unit-tests/function/probability/pickRandom.test.js

Hello, let me know if anything is wrong :)
Fixes #1974

Allow any vector in pickRandom function

---

src/function/utils/clone.js

Since it was missing, and it is important documentation for anyone using math.clone for arrays of arrays (matrices). The deep copying was inferred from the test case, but it shouldn't have been necessary. Now it will hopefully be shown in the doc on the webpage, too.

Update clone.js with doc about deep copying arrays

---

src/type/unit/Unit.js
src/utils/bignumber/constants.js
src/utils/function.js
src/utils/lruQueue.js
test/benchmark/unit_parser.js
test/unit-tests/type/unit/Unit.test.js
test/unit-tests/utils/function.test.js

This fixes some performance issues in my heavily-unit-parsing app.
Another idea might be to do an index of reversed unit names, and search in that, but this is much easier to implement and still should provide an improvement in the majority of cases (since I'd imagine that most users tend to prefer a few units at a time, depending on their application).

Improve performance of _findUnit

---

docs/expressions/syntax.md
src/expression/parse.js
src/type/bignumber/function/bignumber.js
src/type/number.js
test/unit-tests/expression/parse.test.js

I'm working on adding support for numbers with both a non decimal prefix (`0b`, `0o`, or `0x`) and a radix point (`.`) like `0b1.1`.
This should work for `number` and `BigNumber`.

Support for parsing non decimal numbers with radix point

---

src/function/arithmetic/norm.js
src/function/matrix/eigs.js
src/function/matrix/eigs/complexEigs.js
src/function/matrix/matrixFromFunction.js
test/unit-tests/function/matrix/eigs.test.js
test/unit-tests/function/matrix/matrixFrom.test.js

The PRs #1743 and #2155 didn't adhere the _“Array in—Array out, Matrix in—Matrix out”_ principle.
See: [#2155 (comment)](https://github.com/josdejong/mathjs/pull/2155#issuecomment-835750079) and [`e163032` (comment)](https://github.com/josdejong/mathjs/commit/e163032ad2051ee26c617a43d653bb66812b4bd8#commitcomment-50579604)
This PR fixes the problem, the current function annotations are:
```typescript
function eigs(m: number[][]): { values: number[], vectors: number[][] }
function eigs(m: Matrix): { values: Matrix, vectors: Matrix }
function matrixFromFunction(size: number[], fn: Function): Array
function matrixFromFunction(size: Matrix, fn: Function): Matrix
function matrixFromFunction(size: Matrix | number[], format: 'dense' | 'sparse', fn): Matrix
function matrixFromFunction(size: …
```

Fix “AIAO-MIMO” of my previous PRs

---

src/function/matrix/eigs.js
src/function/matrix/eigs/complexEigs.js
test/unit-tests/function/matrix/eigs.test.js

Fixes #2179. There are no changes in the API.

Implemented iterative eigenvalue finder for eigs

---

src/expression/node/ArrayNode.js
test/unit-tests/expression/node/ArrayNode.test.js
test/unit-tests/function/arithmetic/dotDivide.test.js
test/unit-tests/function/arithmetic/dotMultiply.test.js
test/unit-tests/function/arithmetic/dotPow.test.js
test/unit-tests/function/matrix/concat.test.js
test/unit-tests/function/matrix/cross.test.js
test/unit-tests/function/matrix/ctranspose.test.js
test/unit-tests/function/matrix/det.test.js
test/unit-tests/function/matrix/diag.test.js
test/unit-tests/function/matrix/dot.test.js
test/unit-tests/function/matrix/expm.test.js
test/unit-tests/function/matrix/flatten.test.js
test/unit-tests/function/matrix/forEach.test.js
test/unit-tests/function/matrix/inv.test.js
test/unit-tests/function/matrix/map.test.js
test/unit-tests/function/matrix/reshape.test.js
test/unit-tests/function/matrix/resize.test.js
test/unit-tests/function/matrix/rotate.test.js
test/unit-tests/function/matrix/sort.test.js
test/unit-tests/function/matrix/sqrtm.test.js
test/unit-tests/function/matrix/squeeze.test.js
test/unit-tests/function/matrix/subset.test.js
test/unit-tests/function/matrix/trace.test.js
test/unit-tests/function/matrix/transpose.test.js
test/unit-tests/function/probability/pickRandom.test.js
test/unit-tests/function/relational/deepEqual.test.js
test/unit-tests/type/matrix/function/matrix.test.js
test/unit-tests/type/matrix/function/sparse.test.js

This issue was addressed in [this PR](https://github.com/josdejong/mathjs/pull/1542), but it was not merged because the PR included other features whose inclusion has not been finalized. This fix is minimal: just a two-line fix to ensure the row delimiter is added to every row but the last.
The relevant unit tests fail because the expected output includes the trailing `\\` .
Although in regular TeX the trailing `\\` does not change the output, other libraries such as [MathQuill](mathquill.com) (reasonably) interpret this as a blank row:
instead of the expected:

Fix ArrayNode.toTex(): Remove the row delimiter on the last row

---

types/index.d.ts

At runtime, `math.parse('a == b == c').isRelationalNode` is true. Types should reflect this.

add `isRelationalNode` to `MathNode` in types/index.d.ts

---

types/index.d.ts

Some quality-of-life improvements for Typescript users like myself.
Allows instantiation of classes (e.g. `new ConstantNode(5)`)
Corrects the default invocation of `rationalize` (the signatures were in
the wrong order---MathNode is now the default return type)
Makes `create` return a `MathJsStatic` rather than
`Partial<MathJsStatic>` which is painful to use.
Adds convenient aliases for `subtract`
Adds `implicit?: boolean` to MathNode
Makes the `unit` argument on `Unit.toNumber` and `Unit.toNumeric` optional like it is in practice
Represents `math.simplify.rules` and `math.simplify.simplifyCore`
Lets `math.unit` accept `BigNumber`
Potential issue: the constructors return sub-interfaces of MathNode, some of which re-declare properties as no longer optional. In practice, Typescript seems …

Various improvements to the Typescript typings

---

docs/reference/constants.md

Enclose math expressions in ticks to prevent the `*` symbol from being treated as Markdown.

docs: Prevent the `*` symbol from being treated as Markdown.

---

docs/expressions/syntax.md

It says:
An object is enclosed by **square** brackets `{`, `}`,
But they are not square`[`,`]`, they are **curly** `{`, `}`.
The proposal is:
An object is enclosed by curly brackets `{`, `}`,

Changed "square" to "curly"

---

download.md

Change the library website to remove misleading TypeScript separate package reference, now that it is built-in the library.
Fix https://github.com/josdejong/mathjs/issues/2386

docs(gh-pages>download): fix note TypeScript definition

---

src/function/algebra/simplify.js
test/unit-tests/function/algebra/simplify.test.js

Also adds a 'debugConsole' option to simplify() so that it is possible
to see the effect of each rule. This was critical to identifying the problem,
which was that recent changes ended up with `simplifyConstant` in the
wrong position in the list of rules. Correcting that also removed the need
for the two rules coalescing negations with constants.
Resolves #2393.

fix(simplify): Correct regression in simplify

---

css/style.css
history.md
index.md
js/commandline.js

Adjust to the new location of Unit, as math.Unit not math.type.Unit.
Also, use the new api for the parser's scope (getAll() to get all
the identifiers) so that autocompletion of user-defined symbols will
again work.
Finally, when there are multiple matches, cycle through them with
repeated TABs.
Resolves #2434

fix(demo): Restore autocomplete to operation

---

HISTORY.md
types/index.d.ts

This PR updates the type of `math.unit`'s parameter to allow `BigNumber`, and adds types for `Unit.simplify` and `Unit.units`, resolving #2353

`Unit` Typescript type update

---

types/index.d.ts

Reflecting the relocation that happened in 10.2.0

Relocate `simplifyCore` in typing

---

src/function/matrix/map.js
test/unit-tests/function/matrix/map.test.js

Also make the message when there is a type mismatch more detailed,
and add related tests.
Resolves #2436.

doc(map): Clarify the arguments to the callback 

---

src/function/algebra/simplifyCore.js
test/unit-tests/function/algebra/simplifyCore.test.js

Moves the catchall for an arbitrary binary operator node up one level in the
code so that it doesn't let any cases slip through.
Resolves #2461.

fix(simplifyCore): make sure simplifyCore recurses over all binary nodes

---

HISTORY.md
src/function/string/format.js

Found this syntax error on the docs, I am here just to fix it.
https://mathjs.org/docs/reference/functions/format.html

Fix syntax error on example.

---

docs/expressions/algebra.md
docs/expressions/syntax.md
src/expression/operators.js
src/function/algebra/simplify.js
src/function/algebra/simplifyCore.js
test/node-tests/doc.test.js
test/unit-tests/expression/operators.test.js
test/unit-tests/function/algebra/simplify.test.js
test/unit-tests/function/algebra/simplifyCore.test.js

Resolves #2415.
Also fixes a (unreported) typo that prevented getPrecedence of `M'` from returning the correct value.

feat(simplifyCore): convert equivalent function calls into operators

---

src/expression/node/AssignmentNode.js
src/expression/node/ConditionalNode.js
src/expression/node/FunctionAssignmentNode.js
src/expression/node/OperatorNode.js
src/expression/node/RangeNode.js
src/expression/node/RelationalNode.js
src/expression/operators.js
src/expression/parse.js
src/utils/is.js
test/unit-tests/expression/node/OperatorNode.test.js
test/unit-tests/expression/parse.test.js
test/unit-tests/function/algebra/derivative.test.js

As per the discussion in #2370, the amended "Rule 2" is
"when having a division followed by an implicit multiplication, the
division gets higher precedence over the implicit multiplication when
(a) the numerator is a constant with optionally a
prefix operator (-, +, ~), and
(b) the denominator is a constant."
This commit implements that behavior and adds tests for it.
Resolves #2370.

fix(parse): Implement amended "Rule 2"

---

src/expression/parse.js
test/unit-tests/expression/function/parse.test.js

fix(parse): Allow (and ignore) comments wherever white space would be

---

src/function/matrix/eigs/complexEigs.js
test/unit-tests/function/matrix/eigs.test.js

Also adds the test case that revealed the problem and corrects the other test
case that could have found it except the tolerance had been cranked up very
high.
Resolves #2478.

fix(eigs): Track transforms in generating complex eigenvectors

---

HISTORY.md
test/unit-tests/approx.test.js
test/unit-tests/function/trigonometry/sinh.test.js
tools/approx.js

Just let `approx.deepEqual` support `epsilon` so that I can test the precision of lgamma for complex numbers in PR #2417

feat: Improve `approx.deepEqual`, to support epsilon

---

package-lock.json
package.json
test/unit-tests/function/arithmetic/log.test.js

Also adds tests for math.log() of complex numbers in which the imaginary
part is much larger in absolute value than the real part.
Resolves #2503.

chore: Bump complex.js to version 2.1.0

---

src/function/arithmetic/sign.js
src/type/unit/Unit.js
test/unit-tests/expression/parse.test.js
test/unit-tests/function/arithmetic/addScalar.test.js
test/unit-tests/function/arithmetic/multiply.test.js
test/unit-tests/function/arithmetic/sign.test.js
test/unit-tests/function/arithmetic/subtract.test.js
test/unit-tests/type/unit/Unit.test.js

Incorporating unit offsets into the internal "value" of the unit
causes more problems than it solves. This commit ends that practice
and instead only uses the offset when converting units or when
computing the absolute value of a unit.
Further, it makes it an error to compute the sign of a unit with an
offset, since that is inherently ambiguous: there is no way to tell
whether "-5 degC" is a temperature change, in which case it is definitely
negative, or if it is a specific temperature of something, in which case
it is "positive" in the sense of being above absolute zero.
(Unclear how valuable this latter concept is anyway, given that there are
no negative temperatures possible in that sense...)
Adds several tests for the various problems the former practice caused,
including all four …

fix(Unit): Avoid using unit offsets too much

---

docs/expressions/syntax.md

docs(syntax): Highlight `;` and update implicit multiplication

---

test/unit-tests/type/unit/Unit.test.js

This commit captures the cases raised in #2500 as a pending test,
so that it will be easy to re-check them once UnitMath has been
adopted.

test(Unit): record questionable cases for unit multiplication

---

src/factoriesNumber.js
src/plain/number/arithmetic.js
test/node-tests/commonjs.test.js
test/node-tests/commonjsAppNumberOnly.cjs
test/node-tests/esm.test.js
test/node-tests/esmAppNumberOnly.mjs

Provides a number-only factory for `log` with both signatures 'number'
and 'number,number'.
Resolves #2514.

fix: Allow base argument to `log` in number-only module

---

test/unit-tests/function/probability/lgamma.test.js

Right now one unit test on the `develop` branch fail on IE 11. I think this issue was introduced in https://github.com/josdejong/mathjs/pull/2525 and not noticed before since the BrowserStack tests with IE11 only run after merging a PR (because of security reasons).
https://github.com/josdejong/mathjs/runs/6028744969?check_suite_focus=true
```
FAILED TESTS:
lgamma
✖ should calculate the lgamma of a complex number
IE 11.0 (Windows 10)
AssertionError: 20.37669223739772 ~= 20.376692246089224
at fail (eval code:199:3)
at ok (eval code:219:15)
at equal (eval code:41:7)
at deepEqual (eval code:94:5)
at deepEqual (eval code:83:9)
at Anonymous function (eval code:106:5)
```
I made an ugly little workaround for this by testing with less precision on IE11. Does this make sense @gwhitney ? Or do you …

Test lgamma on IE11 with less precision

---

AUTHORS
docs/datatypes/matrices.md
src/factoriesNumber.js
src/function/arithmetic/ceil.js
src/function/arithmetic/fix.js
src/function/arithmetic/floor.js
src/function/arithmetic/nthRoot.js
src/function/arithmetic/round.js
src/plain/number/arithmetic.js
src/type/matrix/function/sparse.js
test/node-tests/commonjs.test.js
test/node-tests/commonjsAppNumberOnly.cjs
test/node-tests/esm.test.js
test/node-tests/esmAppNumberOnly.mjs
test/unit-tests/function/arithmetic/ceil.test.js
test/unit-tests/function/arithmetic/fix.test.js
test/unit-tests/function/arithmetic/floor.test.js
test/unit-tests/function/arithmetic/round.test.js
types/index.d.ts
types/index.ts

This is a sequel to #2531. Uniformizes the signatures of ceil, fix, floor,
and round, and updates the TypeScript declarations to match. Adds the
optional "number of places" argument to the chain versions of ceil, fix,
and floor. Adds TypeScript tests for all rounding functions.
Also corrects the TypeScript declaration for `bignumber()` and introduces
a couple more common abbreviations for TypeScript types.
Fixes the number-only implementations of floor, ceil, fix, and nthRoot
to match the full implementation behavior on numbers, and tests this for
floor.
Includes some minor documentation updates and additional unit tests for
the rounding functions.
Reverts inclusion in AUTHORS of incorrect email for one contributor,
that occurred in #2531.
Resolves #2526.
Resolves #2529.

fix: Type declarations for rounding functions

---

src/function/algebra/resolve.js
test/unit-tests/function/algebra/resolve.test.js
types/index.d.ts
types/index.ts

Noticed that the `resolve` function was missing a type definition. Amazing library @josdejong, nice work 😊

Add TS type for `resolve` function

---

package.json

For issue #2553 
Currently I don't have time to test this, if anyone wants to test, please add following dependencies to a project then try to build, with current version of mathjs it should fail and show the error in issue #2553 , and after this fix it should build successfully.
Currently we have these packages in our dependencies:
"@types/jest": "^27.4.1",
"expect-more-jest": "^5.4.0",
"jest": "^27.5.1",
"jest-mock-extended": "^2.0.4",
"jest-mock-server": "^0.0.5",
"ts-jest": "^27.1.3",
which I think just adding jest and @types/jest would produce the error.
thanks in advance

fix: move @types/mocha to devDependencies

---

tools/docgenerator.js

I noticed that in the generated function reference, the categories `core` and `construction` and function `parse` where missing. This is the case since `mathjs@8.0.0`. I think it occurs since I switched from Linux to Windows, which has different paths, not correctly resolving these function categories.
This PR fixes this in the docgenerator script with a minimal hotfix.
The docgenerator script could use some love: it would be neat to output a warning when no function category could be found (instead of silently ignoring it). Right now, the script matches too many source functions, so to do that (too many functions that need to be on an ignored list). we first must make the glob matching relevant files more specific, and we need to extend the list with functions we want to ignore. …

Hotfix: missing functions in docs

---

README.md
gulpfile.js
package-lock.json
package.json

This is the first step in order to address #2337: making the gh-pages scripts independent of the `examples` and `docs` folder of the publish package on npm.
I'm not sure yet on whether an `npm install` will automatically refresh the installed git source code of the `master` branch, we'll see after the first next release (and if it doesn't work, the `verify` script will fail).

Use the master github branch of mathjs to generate docs and examples

---

src/function/algebra/derivative.js
test/unit-tests/function/algebra/derivative.test.js

Not sure if there's a good reason for this, but currently the expression argument of `derivative(expr,x)`  is not TeX-ified when calling `toTex()` on the derivative node. This is a bit suprising since other functions seems to do this.
Compare the behaviour of `derivative(expr, var)` to `add(x, y)`:
Looks like we're just calling `toString()` when the expression is a `Node`: https://github.com/josdejong/mathjs/blob/develop/src/function/algebra/derivative.js#L132
This PR simply calls toTex on the expression arg if it's a Node

Call `toTex` on expression arg of derivative if it is a node

---

types/index.d.ts
types/index.ts

Adds TReturn generic to MathJsChain and populates it with the return type of whatever chain function returns it
**Example:**
`.done()` now returns correct node type for `complex()`
**Note:** @josdejong   this is just a proof of concept for now to see wha you think. It's obviously not perfect, but I think it's better than the current `any` type that is returned by `done()`. In any case, if the type turns out to be wrong that's always fixable by passing a generic.
Also: I think it maybe be possible to typecheck that each chain function is called on a preceding function returning a valid value, but would have to play around
Also also: I think it may also be possible to not have to duplicate the param types for each chain function as you have now using the [`Parameters` generic …

Improve typing for MathJsChain

---

package.json

Add "types" field to "exports" to fix type imports
I was having trouble getting the mathjs typescript types working in my app:
I previously worked around this by adding this to my tsconfig.json
But that was a bit hacky and started causing other problems, so I decided to figure out what was going on. Seems that the "types" field in package.json is not respected when using "exports". Luckily as of typescript 4.7, "exports" itself supports "types" fields for each declaration as well (see [here](https://github.com/microsoft/TypeScript/issues/33079#issuecomment-1129096299)).
Now, my app is using `type: "module"` so I'm not sure if this will work with the CJS import as well but I assume it will (if someone could check that would be great).
After adding this fix my types now work with no hacks 💥

Fix type import errors due to usage of "exports" in package.json

---

types/index.d.ts
types/index.ts

Adds `TContent` generic arg to ParenthesisNode type so that the type of the content node can be kept track of

Improve ParenthesisNode types

---

types/index.d.ts

Make MathNodeCommon['type'] property a string. This makes it possible to add custom data types, whereas right now Typescript complains that your new node type is not in the built-in union of types.
Before:
After:
I think it's ok to make MathNodeCommon['type'] less strict since each sub type's `type` field is strictly typed and will override `string` from MathNodeCommon

Make MathNodeCommon['type'] property a string

---

types/index.d.ts

Dependencies available in factory callback are now dependent on list of dependencies which are passed in
e.g.
One annoying thing is that you do have to write `const dependencies = ['ArrayNode'] as const` instead of `const dependencies = ['ArrayNode']` so that the type is `readonly ["ArrayNode"]` not `string[]` but that's not so bad I guess?

Improve types for factory function

---

src/type/unit/function/createUnit.js
types/index.d.ts
types/index.ts

Resolves issue #2607
This improves the type definition for `createUnit` function 
I also added an example using `Unit` as definition

fix #2607: improve type definition for createUnit

---

docs/custom_bundling.md

As mentioned in https://github.com/josdejong/mathjs/issues/2683#issuecomment-1220240409.
(Jos, I am not sure how to regenerate the live documentation site, so I didn't merge this PR myself, so that you would see to do the merge and the subsequent regeneration. Thanks.)

doc: fix typos in description of number-only bundle

---

types/index.d.ts
types/index.ts

The TS type for pickRandom currently restricts the given array to numbers, however (AFAIK) it doesn't actually care what the array given to it contains.
This PR:
- Uses a generic to type the given array
- Varies the return type (T or T[]) depending on the given args

Fix types for pickRandom

---

docs/datatypes/units.md

I noticed that in the documentation `min` is marked as short for the volume unit `minim`. This is not the case since it is used as the short form of `minute`. See:
Commented out minim definition:
https://github.com/josdejong/mathjs/blob/194725727a9af7a38a65a0980e4efd16142af8da/src/type/unit/Unit.js#L1896
and the actual minute definition:
https://github.com/josdejong/mathjs/blob/194725727a9af7a38a65a0980e4efd16142af8da/src/type/unit/Unit.js#L2094-L2100
This MR simply moves min to the correct row in the table.

Fix min as short for minim not minute in documentation

---

types/index.d.ts
types/index.ts
types/tsconfig.json

Currently, `MathNode` is defined as a union of all of the existing subclasses of `Node` i.e. 
```ts
type MathNode = MathNo
| AccessorNode
| ArrayNode
| AssignmentNode
| BlockNode
...
```
This has a few consequences:
1. Every time a node new type is added in MathJS you also have to remember to add that type to the `MathNode` union
2. It's impossible (or at least as far as I can tell) to add a custom subclass of `Node` when using mathjs while having that node conform to the `MathNode` type so that TS is happy
By simply aliasing `MathNode` to `MathNodeCommon` (which all existing node types extend), typescript automatically infers that any subclasses of `Node` are valid `MathNode` types.
I did some digging and couldn't quite figure out why the `MathNodeCommon` type needed to exist in the …

Make it possible to create subclass of `Node` while keeping TS happy

---

HISTORY.md
src/function/matrix/flatten.js
test/unit-tests/function/matrix/flatten.test.js

Fix #2793: `math.flatten()` clones object values too

---

src/type/unit/Unit.js

As suggested by @gwhitney in #2821, I made a pull request allowing prefixes to be used for kelvin and rankine units (both in short and in long form).

Allow unit prefixes for (absolute) temperatures (kelvin and rankine)

---

.eslintrc.cjs

When the TS type tests go moved to `tests/` directory, the associated linting rule did not get updated.  Rather than specifically linting TS files in `types/` and `tests/`, I think it's better to just lint all TS files using the TS rules.
Add a linting error in both ts files (index.d.ts and testTypes.ts), run `npm run lint` and check that both errors are caught.

lint ts files in test directory

---

src/function/algebra/simplify.js
test/unit-tests/function/algebra/simplify.test.js

Addresses the rule application limitation aspect as highlighted in issue #2825; such that a broader set of successful standard replacement rules are applied to multi-arg/associative expressions in non-commutative contexts.

Improve standard simplify rule matches in non-commutative contexts

---

src/function/algebra/simplify.js
test/unit-tests/function/algebra/simplify.test.js

These additions permit the valid application of rules to exprs including:
- For new rule 'vd + n*vd -> (1+n)*vd' 'a+2*a' ->  '(1+2)*a'
- And new rule 'cd + cd*n -> cd*(1+n)' '4+4*b' ->  '4*(1+b)'

Simplify: add rules and restructure tests for noncommutative contexts

---

types/index.d.ts

Fix types for `multiply( number[][], number[] )`, `multiply( number[], number[][] )` and `multiply( number[][], number[][] )`
Type errors were introduced to users using `number[]` with #2623, which used MathArray directly (where `MathArray` could be `MathNumericType[]` or `MathNumericType[][]`), causing the return type to be `MathNumericType[] | MathNumericType[][]`, breaking any existing usage of `multiply( number[], number[][] )` and `multiply( number[][], number[][] )`.
The fix in #2623 also didn't fix the case of `multiply( number[], number[][] )`.

Fix types for `multiply()` with `number[]` and `number[][]`

---

test/typescript-tests/testTypes.ts
types/index.d.ts

Issue: #2803 
Why: The type for the function rotationMatrix was missing in index.d.ts
What: Add such type in index.d.ts
Suggestion: Maybe add a type SquareMatrix that extends from Matrix  and the function "rotationMatrix" would return such type ( since rotation matrices are always square ) ?

Fix: Add "rotationMatrix" function type

---

types/index.d.ts

`complex(a)` creates the complex number `a + 0i` when `a` is a non-complex numeric. This should be expressed in the type declaration.

Add numeric types to `complex()` type declaration

---

types/index.d.ts

Please check the issue #2896 
I fixed the last parameter of intersect method to calculate intersection between a line and a plane using typescript.

[fix] intersect method parameter type

---

src/type/unit/Unit.js

Minor change to add `"amps"` and `"amp"` as new aliases for `"ampere"`. Some of our US-based users were surprised that `"1 amp"` or `"5 amps"` wasn't parsed properly, while `"5 volts"` was.

adds additional ampere aliases

---

test/typescript-tests/testTypes.ts
types/index.d.ts

This PR refactors the current type of the gcd function so that the following cases gets warned by Typescript ( which is not currently happening ): 
```javascript
const Xe = [[1,5],[10,49]]
const Ye= [[1,5],[5,7]]
const Re = math.gcd([Xe,Ye]) // it throws, but no warning
const Rc = math.chain([math.complex(3,5),math.complex(6,10)]).gcd().done() // it throws, but no warning
```
GCD accepts an array as a parameters, but their items should not be arrays as well ( though can be matrices )

Fix gcd type

---

test/typescript-tests/testTypes.ts
types/index.d.ts

Addresses https://github.com/josdejong/mathjs/issues/2954
Tests included
And a small typo fix
Couldn't fully run TS tests on local:
```
> mathjs@11.8.0 test:types
> tsc -p ./tsconfig.json && node --loader ts-node/esm ./test/typescript-tests/testTypes.ts
(node:64308) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
/Users/max/mathjs/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:366
throw new ERR_MODULE_NOT_FOUND(
^
CustomError: Cannot find module '/Users/max/mathjs/lib/esm/index.js' imported from /Users/max/mathjs/test/typescript-tests/testTypes.ts
at finalizeResolution (/Users/max/mathjs/node_modules/ts-node/dist-raw/node-internal-modules- …
```

feat: better min/max return type

---

src/function/algebra/simplify.js
test/unit-tests/function/algebra/simplify.test.js

Fix for #2974
Tests included
Added new rule to remove + before - when the term is in parantheses

fix: #2974 Simplify puts plus and minus signs next to eachother

---

src/type/unit/Unit.js

This PR modifies the available prefixes for two units of energy in the library:
**erg** had no prefixes available but we find examples of kiloerg, Merg, and others in the wild like [here](https://en.wikipedia.org/wiki/Template:Convert/list_of_units/energy) and [here](https://lnf-wiki.eecs.umich.edu/wiki/Template:Convert/list_of_units). Adding SHORTLONG prefixes is consistent with the existing unit of bar.
**joule** was set to use SHORTLONG but the short prefixes are not common for this unit. Limiting it to only LONG prefixes is consistent with the existing unit of newton.
Thanks for your consideration!
Carl

Energy prefixes

---

src/expression/embeddedDocs/function/matrix/eigs.js
src/function/matrix/eigs.js
src/function/matrix/eigs/complexEigs.js
src/function/matrix/eigs/realSymmetric.js
test/typescript-tests/testTypes.ts
test/unit-tests/function/matrix/eigs.test.js
types/index.d.ts

For large matrices, the eigenvector computation can be noticeably expensive
and so it's worthwhile to have a way to turn it off if the eigenvectors
will not be used.
Resolves https://github.com/josdejong/mathjs/issues/2180.
Note that this PR is stacked on #3037, so it should only be merged into develop _after_ that one has been.

feat: Add option to eigs() to turn off eigenvector computation

---

src/expression/embeddedDocs/function/arithmetic/round.js
src/function/arithmetic/round.js
test/node-tests/doc.test.js
test/typescript-tests/testTypes.ts
test/unit-tests/function/arithmetic/round.test.js
types/index.d.ts

Implements #2761
With three arguments, the number of different combinations of one or multiple of the arguments being an array explodes quickly. I'm not yet sure which signatures _actually_ make sense. Feedback would be welcome.

Extend function `round` with support for units

---

src/type/unit/Unit.js
test/unit-tests/function/arithmetic/abs.test.js
test/unit-tests/type/unit/Unit.test.js

This is a small bug fix for this problem I discovered:
```javascript
math.unit(1).to('m/m')  // TypeError: undefined is not an object (evaluating 'this.units[0].unit') — Unit.js:831
```
Thanks for considering!
Carl

Unitless quantity conversion bug

---

README.md
src/function/algebra/sparse/README.md
src/function/algebra/sparse/csAmd.js
src/function/algebra/sparse/csChol.js
src/function/algebra/sparse/csCounts.js
src/function/algebra/sparse/csCumsum.js
src/function/algebra/sparse/csDfs.js
src/function/algebra/sparse/csEreach.js
src/function/algebra/sparse/csEtree.js
src/function/algebra/sparse/csFkeep.js
src/function/algebra/sparse/csFlip.js
src/function/algebra/sparse/csIpvec.js
src/function/algebra/sparse/csLeaf.js
src/function/algebra/sparse/csLu.js
src/function/algebra/sparse/csMark.js
src/function/algebra/sparse/csMarked.js
src/function/algebra/sparse/csPermute.js
src/function/algebra/sparse/csPost.js
src/function/algebra/sparse/csReach.js
src/function/algebra/sparse/csSpsolve.js
src/function/algebra/sparse/csSqr.js
src/function/algebra/sparse/csSymperm.js
src/function/algebra/sparse/csTdfs.js
src/function/algebra/sparse/csUnflip.js

See #3162
This PR:
- Adds license information about CSparse in the main README.md
- Adds a README.md file with license information in the `src/function/algebra/sparse` folder
- Replaces the reference links to http://faculty.cse.tamu.edu/davis/publications.html in each of the files under `src/function/algebra/sparse` with license information on top, linking to the github project.

fix #3162: add license information about CSParse

---

examples/browser/pretty_printing_with_mathjax.html

The MathJax example uses `polyfill.io`. The PR replaces `polyfill.io` w/ `cdnjs.cloudflare.com/polyfill`.
---
`polyfill.io` was acquired by **a China-based CDN company** "Funnull", see [the announcement from the `polyfill.io` domain owner's Twitter](https://x.com/JakeDChampion/status/1761315227008643367) and https://github.com/polyfillpolyfill/polyfill-service/issues/2834. Despite Funnull's claims of operating in the United States, the predominance of Simplified Chinese on its website suggests otherwise, and it turns out that **"Funnull" is notorious for providing service for the betting and pornography industries**.
[The original creator of the `polyfill.io` has voiced his concern on Twitter](https://twitter.com/triblondon/status/1761852117579427975). And since the acquisition, numerous …

chore: replace `polyfill.io` inside example

---

docs/expressions/expression_trees.md

Callback function for MathNode.traverse() returns void. Documentation says callback must return a replacement for the existing node (possibly copied from transform() above).

Fix misleading documentation for expression tree traverse

---

src/function/utils/isNaN.js
test/unit-tests/function/utils/isNaN.test.js

Fixes #3192 
This is my first PR on an open project, give as much feedback as you like.
While doing this I realized that this didn't only affect units, but also Complex, BigNumber, etc -> anything that wasn't a straight up number was getting sent directly to the Number.isNaN function, which automatically sets `false` for non-number types.
Also added a test case for this.

Fix NaN for non-number types

---

test/typescript-tests/testTypes.ts
types/index.d.ts

Fixes https://github.com/josdejong/mathjs/issues/3197

Improve quantileSeq typings

---

test/typescript-tests/testTypes.ts
types/index.d.ts

Updates the parser typing based on documentation: https://mathjs.org/docs/expressions/parsing.html#parser
- Added tests to testTypes.ts
https://github.com/josdejong/mathjs/issues/2348
First-time contribution. Please let me know if I am missing anything! Thanks!

fix: updates parser types

---

src/type/unit/Unit.js
test/unit-tests/function/arithmetic/divide.test.js

1 US gallon is defined as 231 cubic inches, which is exactly 3.785411784 L (since 1 inch is defined as 25.4 mm). Other units are defined against the gallon.
I additionally moved the duplicate definitions into aliases.

Use exact values for US liquid volume units

---

src/type/unit/Unit.js
test/typescript-tests/testTypes.ts
types/index.d.ts

- Adds static methods based on documentation: https://mathjs.org/docs/reference/classes/unit.html#unitparsestr--codeunitcode
- Adds static members based on code at `src/type/unit/Unit.js`
- Addresses: https://github.com/josdejong/mathjs/issues/2286
- Added tests to testTypes.ts
I do not see the simplify and format unit in the class documentation. Is it just missing, or am I looking in the wrong place?
- https://mathjs.org/docs/reference/classes/unit.html
- Similarly, the documentation does not reference the following static members.
```
Unit.PREFIXES = PREFIXES
Unit.BASE_DIMENSIONS = BASE_DIMENSIONS
Unit.BASE_UNITS = BASE_UNITS
Unit.UNIT_SYSTEMS = UNIT_SYSTEMS
Unit.UNITS = UNITS
```
- I can take a look at updating the documentation in the future
- Currently, the types I used are pretty …

fix: types static methods and members for Unit class

---

HISTORY.md
src/expression/embeddedDocs/embeddedDocs.js
src/expression/embeddedDocs/function/arithmetic/hypot.js
src/expression/embeddedDocs/function/matrix/diff.js
src/expression/embeddedDocs/function/matrix/fft.js
src/expression/embeddedDocs/function/matrix/ifft.js
src/expression/embeddedDocs/function/matrix/kron.js
src/expression/embeddedDocs/function/special/zeta.js
src/expression/embeddedDocs/function/statistics/quantileSeq.js
src/expression/embeddedDocs/function/trigonometry/acoth.js
src/expression/embeddedDocs/function/trigonometry/acsch.js
src/expression/embeddedDocs/function/utils/clone.js
src/function/arithmetic/hypot.js
src/function/matrix/fft.js
src/function/matrix/ifft.js
src/function/matrix/kron.js
src/function/trigonometry/acoth.js
src/function/trigonometry/acsch.js
test/unit-tests/function/matrix/fft.test.js
test/unit-tests/function/matrix/ifft.test.js
test/unit-tests/function/matrix/kron.test.js
types/index.d.ts

Hi!
I performed a spellcheck on the embedded documents and identified some inconsistencies.
This is a minor correction following the spellcheck.
I don't believe there are any significant issues, primarily just a few words in Spanish that should be in English and similar minor errors.
I'm not a native English speaker so please let me know if I made some mistakes.

Spelling in embedded docs

---

types/index.d.ts

We use a forked version of MathJS in a production deployment, and have customised some functionality of our own. In doing so, we believe we found a mistake in the typescript definition of `ConstantNode`. Per #833 back in 2018, ConstantNode was explicitly extended to allow booleans, nulls, undefined's, etc as values, and [parse.js:1344](https://github.com/josdejong/mathjs/blob/30b195c9b5fe1828591ab90d37eed3af5ea8245e/src/expression/parse.js#L1344) parses such values as ConstantNode. Therefore, I believe ConstantNode's typing should allow more than just `number` and `string` values!

Extend typescript definition for ConstantNode to all types parsed as ConstantNode

---

docs/expressions/syntax.md

Hi,
This adds documentation for `map` and `forEach` in a way to include the compiled inline function syntax.
https://github.com/josdejong/mathjs/discussions/3238#discussioncomment-10407739

Documentation for Map and forEach syntax

---

test/typescript-tests/testTypes.ts
types/index.d.ts

- Fixes MathArray types to allow for n-dimensional arrays.
- Addresses https://github.com/josdejong/mathjs/issues/3098
- Also addresses issue discussed in: https://github.com/josdejong/mathjs/pull/3269#issuecomment-2408328886
https://github.com/josdejong/mathjs/blob/982bbdcb9b4513e4c00db7e8f09e361eeebec678/src/function/arithmetic/multiply.js#L799-L807
- Added n-dimensional type tests
- Updated multiply tests
- PR is made against the v14 release branch
- Continues from: https://github.com/josdejong/mathjs/pull/3099

fix: updates MathArray types to be n-dimensional

---

src/utils/number.js
test/unit-tests/expression/parse.test.js

Fixes https://github.com/josdejong/mathjs/issues/3342#issuecomment-2569624262

Fix: #3342 hexadecimal input not turned into a bigint

---

src/function/arithmetic/log.js
src/function/arithmetic/log10.js
src/function/arithmetic/log2.js
src/function/probability/randomInt.js
src/function/relational/larger.js
src/function/relational/smaller.js
src/function/statistics/max.js
src/function/statistics/min.js
src/function/string/print.js
src/function/utils/isInteger.js
src/utils/bigint.js
test/node-tests/doc.test.js
test/unit-tests/function/arithmetic/log.test.js
test/unit-tests/function/arithmetic/log10.test.js
test/unit-tests/function/arithmetic/log2.test.js
test/unit-tests/function/probability/randomInt.test.js
test/unit-tests/function/relational/larger.test.js
test/unit-tests/function/relational/smaller.test.js
test/unit-tests/function/statistics/max.test.js
test/unit-tests/function/statistics/min.test.js

* Allow a bigint to appear in a max/min of nonhomogeneous arguments
* If randomInt is called with a bigint or a pair of bigints, return a bigint.
* Preserve uniformity of results if randomInt is called with a very large range.
* Extend log, log2, and log10 to bigints.
* Allow mixed Fraction and BigNumber in `smaller` and `larger`.
* Add tests for all of the above issues.
* Bonus: fix one JSDoc comment issue. If every PR fixes one, we will soon get through the 150+ of them.
Resolves #3344.

fix: Handle bigints properly in more cases

---

src/function/arithmetic/ceil.js
src/function/arithmetic/fix.js
src/function/arithmetic/floor.js
src/function/arithmetic/round.js
test/unit-tests/function/arithmetic/ceil.test.js
test/unit-tests/function/arithmetic/fix.test.js
test/unit-tests/function/arithmetic/floor.test.js
test/unit-tests/function/arithmetic/round.test.js

Formerly, it was sufficient for a value x to be within tolerance of its rounded value for that to override the floor/ceil provided by the type of x. Now, we only override that native floor/ceil when the rounded value is within tolerance **and** the floor/ceil value is distinct from x as perceived by the tolerance. When both the rounded value and the floor/ceil are within tolerance, there is no reason to prefer the rounded value over what the native floor/ceil is telling us.
Practically speaking, this change prevents mathjs from becoming confused by the tolerances and reporting that the floor of 1234567890123.5 is 1234567890124. Similar issues for BigNumbers are also fixed. Note this means that with the default tolerances, which are very loose by BigNumber standards, for large BigNumbers …

fix: Don't override type-native floor/ceil within tolerance of value

---

src/expression/transform/index.transform.js
src/function/matrix/range.js
src/type/matrix/MatrixIndex.js
src/type/matrix/Range.js
test/unit-tests/expression/node/IndexNode.test.js
test/unit-tests/expression/parse.test.js
test/unit-tests/function/matrix/range.test.js
test/unit-tests/type/matrix/Index.test.js
test/unit-tests/type/matrix/function/index.test.js

Resolves #3360.
(Since it turns out to be such a small change, I just went ahead and implemented it. If in review there is any concern about the recommended change, to simply accept bigint indices and treat them as the corresponding numbers, it will be easy to modify or retract this.)

fix: Accept bigints in matrix indices and ranges, demoting to number

---

src/type/matrix/DenseMatrix.js
test/benchmark/forEach.js
test/benchmark/map.js

Hi,
This is a faster algorithm for doing Symbol.iterator and some benchmarks. It runs 3 to 4 times faster.
The main changes that increase speed are:
- Don't clone the index in every iteration (just on function calls) about 2.4 times faster
- Don't check if the last dimension is the last dimension on every element of the last dimension about 1.5 times faster

A faster DenseMatrix Symbol.iterator

---

src/utils/optimizeCallback.js
test/unit-tests/type/matrix/DenseMatrix.test.js
test/unit-tests/type/matrix/utils/deepMap.test.js

This is a fix for #3390
If a matrix doesn't have a single type then the optimizeCallback function won't simplify the callback and try to find a single signature.

fix: issue in callback optimization and add error handling for invalid argument types

---

types/index.d.ts

I added the missing `eigsDependencies` entry to the exports in the type definitions. This should fix #3356.

Add missing eigsDependencies export to TypeScript definitions

---

src/type/matrix/DenseMatrix.js

Hi,
This is a refactor of DenseMatrix._forEach method without affecting performance.
This is in preparation for a non indexed version of that method.

Refactor DenseMatrix._forEach

---

src/expression/parse.js
test/unit-tests/expression/parse.test.js

Fixes #3422.
@gwhitney can you review this fix?

fix: #3422 parse dot operators after an implicit multiplication with symbol E

---

src/utils/latex.js
test/unit-tests/type/fraction/function/fraction.test.js

- Addresses #3419 
- Adds fractions to the list of latex functions
- Added a test to ensure toTex results are changed as expected
- Please let me know if I missed any points of documentation that are necessary.
- For the test `math.parse(fraction(a,b)).toTex()` I got back => `\\frac{ a}{\\mathrm{b}}` I assume this is the expected behaviour.

feat: add LaTeX representation for fractions and corresponding tests

---

src/type/matrix/DenseMatrix.js

Hi,
This PR includes performance improvements in both `.map` and `.forEach` methods in DenseMatrix by separating the logic and avoiding cloning of a matrix. Opting for a create and resize.
```
abs(genericMatrix)                               2.03 µs   ±0.17%
abs(array)                                       1.11 µs   ±0.53%
abs(numberMatrix)                                2.06 µs   ±0.18%
genericMatrix.map(abs)                           5.14 µs   ±0.18%
numberMatrix.map(abs)                            5.17 µs   ±0.18%
map(genericMatrix, abs)                          5.18 µs   ±0.17%
map(numberMatrix, abs)                           5.21 µs   ±0.20%
map(array, abs)                                  4.33 µs   ±0.17%
map(array, abs.signatures.number)                1.79 µs   ±0.31% …
```

Dense matrix increase performance of map and forEach

---

docs/expressions/syntax.md
src/expression/parse.js
test/unit-tests/expression/parse.test.js

This is a fix/change to https://github.com/josdejong/mathjs/discussions/3349
This gives unary `%` operator (percentage) higher precedence than binary `%` operator (modulo). This also makes unary `%` operator have higher precedence than `*`, `/`, `.*`, `./`, and `mod` operators.
This partially rolls back changes from #3311; however, intended behavior from that change is preserved: the precedence of binary `%` operator (modulo) has _not_ changed. For example, `11*12%13` is still treated as `(11*12)%13`, whereas in MathJS v13 it was treated as `11*(12%13)`.
This is a **BREAKING CHANGE** and should get a new major version:
- v13: `100 / 50%` = `100 / (50%)` = `100 / 0.5` = `200`
- v14: `100 / 50%` = `(100 / 50)%` = `2%` = `0.02`
- this PR: `100 / 50%` = `100 / (50%)` = `100 / 0.5` = `200` …

feat: give unary % operator (percentage) higher precedence than binary % operator (modulus)

---

HISTORY.md
src/type/unit/Unit.js
test/unit-tests/type/unit/Unit.test.js

This is a workaround for #3450.
Note that for the `.multiply` method, it is possible to elimitate the temporarily introduced numbers `1`, but for `.divide` that isn't possible, therefore I kept using the `1` values in both.

fix: the internal number conversion inside `Unit` can throw an exception

---

src/type/matrix/DenseMatrix.js
test/benchmark/subset.js

Hi,
This improves the speed of subset by following a recommendation in the TODO comments and other recursion improvements.
These are the results
```
develop
======
subset(matrix, rows and columns)         1.89 µs   ±0.13%
subset(array, rows and columns)          4.89 µs   ±0.25%
subset(matrix, booleans and columns)     2.15 µs   ±0.25%
subset(array, booleans and columns)      5.09 µs   ±0.14%
subset(matrix, columns and booleans)     2.15 µs   ±0.35%
subset(array, columns and booleans)      5.13 µs   ±0.34%
subset(matrix, range and rows)           1.19 µs   ±0.20%
subset(array, range and rows)            4.19 µs   ±0.16%
subset(matrix, range and all)            1.73 µs   ±0.20%
subset(array, range and all)             4.70 µs   ±0.16%
subset(matrix, all and range)            2.32 µs …
```

Faster subset

---

src/expression/parse.js
test/unit-tests/expression/parse.test.js

This is a little fix for #3474 to allow correct parsing (avoid syntax error) of compound units ending with `in` but not the end of the line, for example `(2 lbf in)`
Thanks for considering.
Carl

Correctly parse (lbf in)

---

src/expression/parse.js
test/unit-tests/expression/parse.test.js

This PR fixes #3501 using the approach suggested in the discussion of that issue: when a % is encountered, the parse now looks to see if there is a valid term just past the %, using only operators with higher precedence than %. If so, it concludes the % must be binary modulus; if not, it interprets the % as unary percentage. It appears that this approach succeeds as hoped.
Note this change flips the interpretation of two prior unit tests: `3%+100` was interpreted as `(3%) + 100` but it is now interpreted as `3 mod +100`; similarly, `3%-100` goes from `(3%) - 100` to `3 mod -100`. On the other hand, it now properly allows the expression `3%~1`, evaluating it as `3 mod -2` (since the value of the bitwise negation `~1` is -2; this expression was previously a syntax error.
Further, this …

fix: parse % as unary only when not followed by a term

---

src/expression/parse.js
test/unit-tests/expression/parse.test.js

Fixes #3421
A simple solution is to not only parse hex characters, but just parse any alpha and digit character after the prefix `0x`, `0o`, or `0x`, and then try to parse the string into a number. When evaluating `0x1k`, this will give an error messate "SyntaxError: String "0x1k" is not a valid number". 
An alternative solution would be to create separate flows for parsing `hex`, `oct`, and `bin`, with specific functions `isHexDigit`, `isOctDigit` and `isBinDigit`, and then we need a separate check to see if the value is followed by an alpha or digit character and then throw an error like "Unexpected character 'k' (char: 3)". I think though that the former is a more informative error message.
@gwhitney can you have a brief look at this PR?

fix: #3421 require a space or delimiter after hex, bin, and oct values

---

src/function/arithmetic/sign.js
test/unit-tests/function/arithmetic/sign.test.js

```
math.sign(0) // gives 0 ✅
math.sign(math.complex(0,0)) // gives 0+0i ✅
math.sign(math.fraction(0)) // gives 1/1 ❌, it should give 0/1 
```
issue where math.sign(math.fraction(0)) incorrectly returned 1/1 instead of 0/1. Changed fraction sign detection from checking x.s to checking x.n === 0n (numerator is 
/function/arithmetic/sign.js:55 - Changed from `return new Fraction(x.s)` to `return x.n === 0n ? new Fraction(0) : new Fraction(x.s)`
test/unit-tests/function/arithmetic/sign.test.js:108-110 - Added test case for `math.sign(math.fraction(0))`

sign of zero fraction should return 0/1 instead of 1/1

---

src/core/function/config.js

Addresses #3538. I'm surprised we didn't catch this earlier 😅.

fix: #3538 `config` printing a warning when using `{ number: 'bigint' }`

---

test/typescript-tests/testTypes.ts
types/index.d.ts

The absolute value of a complex number is a plain number.

Fix types of abs(complex)
