josdejong/mathjs

lib/util/bignumber.js, test/function/trigonometry/sin.test.js
I never pushed the changes I discussed. Hopefully none of this looks foreign since we discussed most of this.
=> Big Sin slight update.

lib/function/probability/factorial.js, test/function/probability/factorial.test.js, test/function/probability/gamma.test.js
=> Fix factorial round-off errors, and correct the output of 'Infinity!'.

lib/function/trigonometry/cos.js, lib/function/trigonometry/sin.js, lib/util/bignumber.js, test/function/trigonometry/cos.test.js, test/function/trigonometry/sin.test.js
Improved the speed of sine, and added cosine. I also adjusted the file, so that relevant functions are bunched together; it helped me keep track of my helper functions. I also checked all of the commented out test cases, and their output values are correct for their input values.
=> Big sine and cosine

docs/expressions/syntax.md
Sorry this was a short and dirt PR using GitHub and I was too fast (this isn't anything relevant so hopefully it's okay to make the PR directly to master :/ )
=> [3,6,9] for 1*3,2*3,3*3

lib/function/trigonometry/acos.js, lib/function/trigonometry/acosh.js, lib/function/trigonometry/acot.js, lib/function/trigonometry/acoth.js, lib/function/trigonometry/acsc.js, lib/function/trigonometry/acsch.js, lib/function/trigonometry/asec.js, lib/function/trigonometry/asech.js, lib/function/trigonometry/asin.js, lib/function/trigonometry/asinh.js, lib/function/trigonometry/atan.js, lib/function/trigonometry/atanh.js, lib/math.js, lib/util/bignumber.js, test/function/trigonometry/acosh.test.js, test/function/trigonometry/acot.test.js, test/function/trigonometry/acoth.test.js, test/function/trigonometry/acsc.test.js, test/function/trigonometry/asec.test.js, test/function/trigonometry/asech.test.js, test/function/trigonometry/asin.test.js, test/function/trigonometry/atan.test.js, test/function/trigonometry/atanh.test.js
Also fixed handles atan(+/-i).
=> acsc, asec, acot, and added Complex returns for expression parser

lib/expression/node/AssignmentNode.js, lib/expression/node/ConditionalNode.js, lib/expression/node/FunctionAssignmentNode.js, lib/expression/node/FunctionNode.js, lib/expression/node/Node.js, lib/expression/node/OperatorNode.js, lib/expression/node/RangeNode.js, lib/expression/operators.js, test/expression/node/AssignmentNode.test.js, test/expression/node/ConditionalNode.test.js, test/expression/node/FunctionAssignmentNode.test.js, test/expression/node/FunctionNode.test.js, test/expression/node/Node.test.js, test/expression/node/OperatorNode.test.js, test/expression/node/RangeNode.test.js, test/expression/operators.test.js, test/expression/parse.test.js
See #290 
One thing is still unclear: Should `getPrecedence`, `getAssociativity` and `isAssociativeWith` be added to `Node.prototype`?
=> New generic implementation of toString

lib/expression/node/AssignmentNode.js, lib/expression/node/FunctionAssignmentNode.js, lib/expression/node/OperatorNode.js, test/expression/node/AssignmentNode.test.js, test/expression/node/FunctionAssignmentNode.test.js, test/expression/node/FunctionNode.test.js, test/expression/node/OperatorNode.test.js
This should be ok for now.
But the code in `lib/util/latex.js` really requires some love! ( But that requires that I actually fully understand it first ).
=> Update toTex to better handle parenthesis

gulpfile.js
Resolves #300 
I didn't bother updating the dist files, I figured that's usually handled before publishing a new version.
=> Fix Source Map Location

lib/util/latex.js, test/util/latex.test.js
This fixes an exception caused by symbols with indices. ( including a test that covers this case )
=> Fix bug that was introduced by the restructuring of the LaTeX code

bin/cli.js
This adds `--tex` and `--string` command line parameters to `cli.js` and enables the use of multiple script files. (see #295)
=> `toTex` and `toString` support for the command line interface

lib/function/combinatorics/bellNumbers.js, lib/math.js, lib/util/latex.js, test/function/combinatorics/bellNumbers.test.js
Adding support for Bell Numbers + test.
=> [Combinatorics] Support for Bell Numbers

test/function/trigonometry/cot.test.js
See [issue](https://github.com/josdejong/mathjs/issues/355) for reference.
Closed [last PR](https://github.com/josdejong/mathjs/pull/356) since I tried to merge it into master and not develop.
=> Deleting console.log statement

lib/expression/docs/function/algebra/lsolve.js, lib/expression/docs/function/algebra/lup.js, lib/expression/docs/function/algebra/lusolve.js, lib/expression/docs/function/algebra/usolve.js, lib/expression/docs/index.js, lib/function/algebra/decomposition/lup.js, lib/function/algebra/index.js, lib/function/algebra/solver/lsolve.js, lib/function/algebra/solver/lusolve.js, lib/function/algebra/solver/usolve.js, lib/type/matrix/util/algorithm04.js, test/function/algebra/solver/lsolve.test.js, test/function/algebra/solver/usolve.test.js
- `lsolve()` - Solves the linear system L * x = b, where L is a lower triangular Matrix
- `usolve()` - Solves the linear system U * x = b, where U is an upper triangular Matrix
- small performance improvement in `algorithm04()`
- documentation updates
=> Algebra updates / additions

docs/reference/functions/randomInt.md
Fixing readability referenced [here](https://github.com/josdejong/mathjs/issues/381).
=> Making randomInt's documentation more readable

lib/expression/docs/function/geometry/intersect.js, lib/expression/docs/index.js, lib/function/geometry/intersect.js, lib/math.js, test/function/geometry/intersect.test.js
Computes:
- Line and line intersection in 2D and 3D
- Line and plane intersection in 3D
Also created folder `geometry` for `intersect.js`
=> Added intersection function

lib/function/arithmetic/nthRoot.js, test/function/arithmetic/nthRoot.test.js
working on nthRoot for complex numbers. (De Moviers)
=> Complex Roots

lib/expression/docs/function/statistics/mode.js, lib/function/statistics/index.js, lib/function/statistics/mode.js, test/function/statistics/mode.test.js
- Added the function in mode.js
- wrote the test cases.
Deleted the old pull request #399. Wrote this function in the v2 format.
=> Added Mode Function

docs/datatypes/units.md, docs/expressions/syntax.md, docs/reference/units.md, examples/basic_usage.js, examples/units.js, lib/function/arithmetic/divideScalar.js, lib/function/arithmetic/multiplyScalar.js, lib/function/arithmetic/pow.js, lib/type/unit/Unit.js, test/function/arithmetic/divide.test.js, test/function/arithmetic/dotDivide.test.js, test/function/arithmetic/multiply.test.js, test/function/arithmetic/pow.test.js, test/function/units/to.test.js, test/type/unit/Unit.test.js, test/type/unit/function/unit.test.js
Here's a first attempt at derived units. (See issue #13.) I've also added new unit tests. Check out the updated examples. I think temperatures might not work altogether correctly yet, so will need to add some unit tests to that effect.
Also, any recommendations on an editor for .md files? I'm assuming you'd like some help eventually updating those.
=> Derived units

lib/type/unit/physical_constants.js, test/type/unit/constants.test.js
Noticed the speed of light was wrong. I haven't checked any of the other constants.
=> Fixed speed of light constant

lib/type/unit/physical_constants.js, test/type/unit/constants.test.js
This was the only other mistake I found.
=> Fixed molar mass of C12

lib/function/arithmetic/nthRoot.js, test/function/arithmetic/nthRoot.test.js
=> Replaced nthRoot algorithm with direct calculation

lib/type/unit/Unit.js
Change PLURALS to ALIASES, clean up manual aliases. Add new angle units arcmin and arcsec, along with appropriate aliases.
=> PLURALS -> ALIASES, add arcmin, arcsec

docs/reference/units.md, lib/type/unit/Unit.js
As described in #520. Just a simple addition of units -- the more complex case can be considered later.
=> Add time units (Issue #520)

lib/expression/node/ObjectNode.js, test/expression/node/ObjectNode.test.js
This is my current approach, tell me if I should change something.
Example:
=> ObjectNode: prettier LaTeX output

lib/core/import.js
=> import BigNumber, Fraction, Matrix, and Array

docs/datatypes/units.md, lib/type/unit/Unit.js
I've added the kip/kips unit as requested by @olimortimer in https://github.com/josdejong/mathjs/issues/554
=> Add kip unit

lib/type/unit/Unit.js
- Enables units like 'nanomoles'
=> Add prefixes to moles

lib/function/utils/index.js, lib/function/utils/isNaN.js, test/function/utils/isNaN.test.js
=> New function 'isNaN'

lib/function/utils/index.js, lib/function/utils/isPrime.js, test/function/utils/isPrime.test.js
* Allows to check if numbers (including bignumbers) are prime 
* Included tests
Let me know if this is useful! I'm new to this whole open-source thing, so let me know what I can work or improve. Thanks :)
=> Added isPrime method, to check to see if numbers are prime

lib/function/utils/isPrime.js
Fixed the bignumber implementation in isPrime. Hope this is good!
=> Fix bignumber isPrime implementation to use bignumber methods

package.json
=> update contributor list

docs/expressions/syntax.md
=> Changed ',' to ';' in doc's to fix typo

docs/expressions/syntax.md
The comments now represent the result of each line of code.
I added some extra lines to show the value of the string `a` after each modification to it.
=> Changed expressions/syntax in docs to represent the actual result of string operations.

lib/expression/node/OperatorNode.js, test/expression/node/OperatorNode.test.js
=> OperatorNode: fix: implicit multiplication was not cloned

lib/function/statistics/index.js, lib/function/statistics/mad.js, test/function/statistics/mad.test.js
New PR to merge with develop branch :)
=> Add median absolute deviation

lib/function/matrix/index.js, lib/function/matrix/kron.js, test/function/matrix/kron.test.js
Adds Kronecker Product as math.kron(x, y);
From issue #704
=> Add Kronecker Product (Direct / Tensor Product)

docs/core/configuration.md, index.js, lib/core/core.js
=> fixed doc error for config option predictable

lib/function/algebra/simplify.js, test/function/algebra/simplify.test.js
=> Fixed simplify to recognize named constants

lib/utils/function.js
Changed the comment tag from `/*` to `/**`
=> just a typo fix for mismatching comment tags to relieve my OCD

lib/function/algebra/index.js, lib/function/algebra/rationalize.js, test/function/algebra/rationalize.test.js
Unfortunately, my workflow in this project was stupid, because never in my life I've worked in a shared project (`GitHub` or `SourceForge`). So brench, fork, clone (in that sense), pull request, push (in that sense), commit (in that sense) it was all greek words for me.
So I worked in the cloud (`GitHub` site).  I had cloned to local folder only to change the flles locally and testing locally . 
However, I don't used the `commit` command.  I've changed the files locally, tested them using my local    `mocha ` and manually copy the changed files to my repository in the cloud.
Now, I guess that it is different. It's much easier, but know I know ....
Steps that I've followed:
**1)** I Downloaded `GitHub DeskTop` . I'm tired of command line mode.
**2)** I went to original ( …
=> Rationalize. Is it almost ready?

lib/function/geometry/distance.js, lib/function/geometry/intersect.js, test/function/geometry/distance.test.js, test/function/geometry/intersect.test.js
This PR fixes  #992 . 
`distance` and `intersect` functions from geometry package now can work with big numbers.
=> Added BigNumber support for distance() and intersect() functions

lib/expression/node/ConstantNode.js, lib/utils/latex.js, package-lock.json, package.json, test/expression/node/ConstantNode.test.js, test/utils/latex.test.js
See #995 
Still waiting for a new release of escape-latex and a bugfix (that's why the tests are failing).
=> Escape string in toTex

docs/reference/functions/print.md, lib/function/string/print.js, test/function/string/print.test.js
I can write the tests, can't think of anything else than duplicating the existing ones with arrays instead of objects.
=> Add support for Array values argument in print function

lib/function/matrix/inv.js, test/function/matrix/inv.test.js
=> Add pivoting to matrix inverse algorithm, and tests

lib/function/matrix/inv.js, test/function/matrix/inv.test.js
=> inv bug fix

docs/datatypes/complex_numbers.md, src/type/complex/function/complex.js, test/type/complex/function/complex.test.js
Updated docs and added support for math.complex({abs: ..., arg: ..})
=> complex.js integration #964

docs/datatypes/units.md
There was a broken link that should be fixed with this commit
=> fix format link in units page

HISTORY.md
Thanks @stropitek for flagging this in #1156.
=> fix spelling my name :fearful:

src/expression/parse.js
I had a go at doing some tidying up in parse.js.
To that end I have removed the use of global state from the file, instead each function now takes a state object as a parameter and modifies that. Hopefully, this change makes the code easier to follow and modify in the future.
I have added a description to each of the commits messages, it might be easier to review each commit seperately.
=> Improve management of state in parse.js

css/style.css
Added css for table and td/th to make it fixed inside its container
Check following URL for the issue:
http://mathjs.org/docs/reference/functions/typeof.html
=> Fixed ui issue with table on Function typeof detail page of mathjs website

package.json
=> chore(package): update tar to version 4.4.6

docs/expressions/syntax.md, src/expression/parse.js, test/expression/parse.test.js
This seems to do the job :) (feature request #816)
Edit: basically I just duplicated the double quotes string step, inserted it into the pipeline
=> Add support for single quotes strings

src/type/unit/Unit.js
=> Fix unit rod

src/type/unit/Unit.js, test/type/unit/Unit.test.js
=> Fixed unit base recognition and formatting for user-defined units

src/utils/latex.js, test/function/bitwise/bitNot.test.js
=> bitNot: Fix incorrect tilde in LaTeX output

src/utils/number.js, test/utils/number.test.js
=> Fix #1337: function format precision 0 bug

HISTORY.md
Because fraction.js is bundled up into the script that mathjs ships maybe we should record when we upgrade it in HISTORY.md.
This would be the same for all (non dev) dependencies.
I am mainly making this PR to ask the question: is this something that we should do?
=> Add upgraded dependancy to HISTORY.md

README.md
As it is no longer 2018 this badge is currently claiming mathjs is stale
=> Let folk know that mathjs is still maintained

package.json
I did this ages ago in https://github.com/josdejong/mathjs/pull/1316 but it snuck back in 😱
=> remove dev dep on tar

.travis.yml
Only run local tests in pull requests and only run browser tests
when running in a branch.
Should speed up ci runs slightly.
(maybe) closes #1139
=> Only one job for browser tests on travis

package-lock.json, package.json
=> Greenkeeper/expr eval 2.0.1

test/benchmark/factorial.js
=> [WIP] improve bigFactorial algorithm

HISTORY.md, src/expression/Help.js, src/function/algebra/simplify.js, src/type/unit/Unit.js, test/node-tests/lib.test.js, test/node-tests/polluted_object_prototype.js, test/unit-tests/expression/Help.test.js, test/unit-tests/type/unit/Unit.test.js
=> Fix #1856: make the library robust against Object prototype pollution

examples/browser/pretty_printing_with_mathjax.html
Upgrades to MathJax v3 and adjusts to new APIs.
Resolves #2022
=> docs: update pretty print with MathJax

src/type/unit/Unit.js, test/unit-tests/type/unit/Unit.test.js
=> adding kilogramforce aka kgf unit

src/function/algebra/solver/lsolveAll.js, src/function/algebra/solver/usolveAll.js
The overleaf link in the comments of `usolveAll` and `lsolveAll` didn't work.
=> fixed a link in the comments of usolveAll and lsolveAll

src/function/probability/pickRandom.js
https://github.com/josdejong/mathjs/issues/2174#issue-855894295
=> Fixed the bug that pickRandom has no name.

types/index.d.ts
=> Adds types for eigs function

package.json
=> Add types to `files` for publishing to npm

README.md
=> Remove note about needing to install @types/mathjs package

types/index.d.ts, types/index.ts
See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52648
=> Add types for custom parsing functions

types/index.d.ts, types/index.ts
This PR fixes the issue mentioned in [#2271](https://github.com/josdejong/mathjs/issues/2271)
=> Adding type definition for hasNumericValue

types/index.d.ts
`isConditionalnode` → `isConditionalNode`
=> Fix typo in isConditionalNode in types/index.d.ts

src/utils/object.js
Issue #2300
deepStrictEqual was called twice for each property
=> Fix performance problem with deepStrictEqual

src/function/probability/gamma.js, test/unit-tests/function/probability/gamma.test.js
=> fix(gamma function): use reflection formula to handle negative values

types/index.d.ts, types/index.ts
Hi! :) Please add this TS overload, thanks!
=> Added unit(unit: Unit) TS overload

src/expression/embeddedDocs/function/matrix/forEach.js
Included example as a reference that works inside the expression parser
=> Included example for embedded documentation

AUTHORS
Two mails of mine are mentioned. I removed the incorrect/unnecessary mail address
=> Removed the incorrect mail of mine

types/index.d.ts
This is a fixed version of https://github.com/josdejong/mathjs/pull/2592
=> Types/improve factory dependencies (fixed)

types/index.d.ts, types/index.ts
Hi Jos,
I'm working with Matt and Jacob on GoodProblems.
This addresses discussion [#2600].(https://github.com/josdejong/mathjs/discussions/2600). 
Let me know if there is anything I should change or if there is anything else I can add 🙂
=> Add missing types for simplify rules

docs/core/chaining.md, src/core/create.js, src/core/function/import.js, src/core/function/typed.js, src/function/matrix/ones.js, src/function/matrix/zeros.js, src/type/chain/Chain.js, test/unit-tests/type/chain/Chain.test.js, types/index.d.ts, types/index.ts
As discussed in #2476.
Resolves #2485.
=> Prevent chain functions from matching stored value with a rest parameter

types/index.d.ts, types/index.ts
=> fix #2621: Module "mathjs" has no exported member "count" .ts(2305)

types/index.d.ts
- fixed min func wrong type defs
=> 🔧 fixed typos in `min` func type defs

types/index.d.ts, types/index.ts
=> fix(pinv): write a typescript definition and test

src/type/matrix/SparseMatrix.js, test/unit-tests/type/matrix/SparseMatrix.test.js
As discussed in #2830 and corrected formatting
=> Prevent inserting zero values in SparseMatrix

types/index.d.ts
This PR refactors some types in the index.d.ts file to use generics to achieve the same type restrictions but with less lines of code.
=> Refactor index.d.ts

docs/expressions/parsing.md, src/expression/Parser.js, src/expression/function/parser.js
=> Fix typo in doc

src/function/geometry/distance.js, test/unit-tests/function/geometry/distance.test.js, types/index.d.ts
some additional unit tests, types and doc fix for distance function
=> fix: distance from point to line

docs/datatypes/units.md, src/type/unit/Unit.js, test/unit-tests/type/unit/Unit.test.js
See https://github.com/josdejong/mathjs/issues/3112
=> Support new metric prefixes: Q, R, r, and q

types/index.d.ts
Addressed silentmissile's comment in:
https://github.com/josdejong/mathjs/issues/3125
=> Improve type definitions of function `hypot`

_layouts/default.html, css/style.css
=> Change font

docs/expressions/customization.md
Commit 35329d7db4797765595d4fb5091407d114b1fb0c moved the location of `parse.js`. This PR adjusts sources to changes.
=> docs: update `parse.js` reference
